-- For sqlc only, not a migration: the version table that goose creates before
-- it applies the first migration (PostgreSQL dialect), with one row per
-- migration applied.
CREATE TABLE goose_db_version (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  version_id bigint NOT NULL,
  is_applied boolean NOT NULL,
  tstamp     timestamp NOT NULL DEFAULT now()
);
