/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the version of the running server
         * @description Returns the release version and Git commit of the running server, and
         *     the version of this API. It needs no authentication, so clients can
         *     check compatibility before logging in.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the calling principal
         * @description Returns the principal that makes the request and its roles. Plan
         *     P1-03 adds its permissions and the CSRF token of the session.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VersionInfo: {
            /** @description Release version, or `dev` for local builds. */
            version: string;
            /** @description Git commit the binary was built from, or `unknown`. */
            commit: string;
            /**
             * @description Version of this API.
             * @enum {string}
             */
            apiVersion: "v1";
        };
        Principal: {
            /**
             * Format: uuid
             * @description The principal's identifier.
             */
            id: string;
            /** @enum {string} */
            kind: "human" | "service_account";
            displayName: string;
            /** @description The roles bound to the principal (requirements, permission matrix). */
            roles: string[];
        };
        /**
         * @description RFC 9457 problem details. `type` and `code` identify the error;
         *     `title` is the same for every occurrence of it, and `detail`
         *     explains this one. No internal detail reaches the client.
         */
        Problem: {
            /**
             * Format: uri
             * @description Identifies the error, and links to its documentation.
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description This occurrence, as `urn:uuid:` followed by the request ID, which the logs record. */
            instance?: string;
            /** @description The stable error code. */
            code: string;
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version of the running server. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The calling principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
