// Module contracts v0.1 (RFC-0001): evidence from module instances.
// Normative text: docs/contracts/module-contract-v0.1.md, section 8.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whitetower/module/v1alpha1/events.proto

package modulev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "whitetower.module.v1alpha1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServicePublishProcedure is the fully-qualified name of the EventService's Publish RPC.
	EventServicePublishProcedure = "/whitetower.module.v1alpha1.EventService/Publish"
)

// EventServiceClient is a client for the whitetower.module.v1alpha1.EventService service.
type EventServiceClient interface {
	// Publish delivers a batch of events. Delivery is at least once: the core
	// de-duplicates on the event's source and ID, so a batch can be retried
	// as is.
	Publish(context.Context, *connect.Request[v1alpha1.PublishRequest]) (*connect.Response[v1alpha1.PublishResponse], error)
}

// NewEventServiceClient constructs a client for the whitetower.module.v1alpha1.EventService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_events_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		publish: connect.NewClient[v1alpha1.PublishRequest, v1alpha1.PublishResponse](
			httpClient,
			baseURL+EventServicePublishProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Publish")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	publish *connect.Client[v1alpha1.PublishRequest, v1alpha1.PublishResponse]
}

// Publish calls whitetower.module.v1alpha1.EventService.Publish.
func (c *eventServiceClient) Publish(ctx context.Context, req *connect.Request[v1alpha1.PublishRequest]) (*connect.Response[v1alpha1.PublishResponse], error) {
	return c.publish.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the whitetower.module.v1alpha1.EventService service.
type EventServiceHandler interface {
	// Publish delivers a batch of events. Delivery is at least once: the core
	// de-duplicates on the event's source and ID, so a batch can be retried
	// as is.
	Publish(context.Context, *connect.Request[v1alpha1.PublishRequest]) (*connect.Response[v1alpha1.PublishResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_events_proto.Services().ByName("EventService").Methods()
	eventServicePublishHandler := connect.NewUnaryHandler(
		EventServicePublishProcedure,
		svc.Publish,
		connect.WithSchema(eventServiceMethods.ByName("Publish")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	return "/whitetower.module.v1alpha1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServicePublishProcedure:
			eventServicePublishHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) Publish(context.Context, *connect.Request[v1alpha1.PublishRequest]) (*connect.Response[v1alpha1.PublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.EventService.Publish is not implemented"))
}
