// Module contracts v0.1 (RFC-0001): governance state, leases and acknowledgements.
// Normative text: docs/contracts/module-contract-v0.1.md, sections 5 and 6.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whitetower/module/v1alpha1/governance.proto

package modulev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GovernanceServiceName is the fully-qualified name of the GovernanceService service.
	GovernanceServiceName = "whitetower.module.v1alpha1.GovernanceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GovernanceServiceWatchProcedure is the fully-qualified name of the GovernanceService's Watch RPC.
	GovernanceServiceWatchProcedure = "/whitetower.module.v1alpha1.GovernanceService/Watch"
	// GovernanceServiceAcknowledgeProcedure is the fully-qualified name of the GovernanceService's
	// Acknowledge RPC.
	GovernanceServiceAcknowledgeProcedure = "/whitetower.module.v1alpha1.GovernanceService/Acknowledge"
)

// GovernanceServiceClient is a client for the whitetower.module.v1alpha1.GovernanceService service.
type GovernanceServiceClient interface {
	// Watch streams the governance state of every agent in the instance's scope:
	// a snapshot, then changes in version order, with lease renewals in between.
	// The stream never ends on its own except when the token that opened it
	// expires or the server shuts down; clients reconnect and resume.
	Watch(context.Context, *connect.Request[v1alpha1.WatchRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchResponse], error)
	// Acknowledge reports what the instance did with the state it received:
	// halt layers, bundle activations and the state version applied.
	Acknowledge(context.Context, *connect.Request[v1alpha1.AcknowledgeRequest]) (*connect.Response[v1alpha1.AcknowledgeResponse], error)
}

// NewGovernanceServiceClient constructs a client for the
// whitetower.module.v1alpha1.GovernanceService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGovernanceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GovernanceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	governanceServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_governance_proto.Services().ByName("GovernanceService").Methods()
	return &governanceServiceClient{
		watch: connect.NewClient[v1alpha1.WatchRequest, v1alpha1.WatchResponse](
			httpClient,
			baseURL+GovernanceServiceWatchProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		acknowledge: connect.NewClient[v1alpha1.AcknowledgeRequest, v1alpha1.AcknowledgeResponse](
			httpClient,
			baseURL+GovernanceServiceAcknowledgeProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("Acknowledge")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
	}
}

// governanceServiceClient implements GovernanceServiceClient.
type governanceServiceClient struct {
	watch       *connect.Client[v1alpha1.WatchRequest, v1alpha1.WatchResponse]
	acknowledge *connect.Client[v1alpha1.AcknowledgeRequest, v1alpha1.AcknowledgeResponse]
}

// Watch calls whitetower.module.v1alpha1.GovernanceService.Watch.
func (c *governanceServiceClient) Watch(ctx context.Context, req *connect.Request[v1alpha1.WatchRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// Acknowledge calls whitetower.module.v1alpha1.GovernanceService.Acknowledge.
func (c *governanceServiceClient) Acknowledge(ctx context.Context, req *connect.Request[v1alpha1.AcknowledgeRequest]) (*connect.Response[v1alpha1.AcknowledgeResponse], error) {
	return c.acknowledge.CallUnary(ctx, req)
}

// GovernanceServiceHandler is an implementation of the whitetower.module.v1alpha1.GovernanceService
// service.
type GovernanceServiceHandler interface {
	// Watch streams the governance state of every agent in the instance's scope:
	// a snapshot, then changes in version order, with lease renewals in between.
	// The stream never ends on its own except when the token that opened it
	// expires or the server shuts down; clients reconnect and resume.
	Watch(context.Context, *connect.Request[v1alpha1.WatchRequest], *connect.ServerStream[v1alpha1.WatchResponse]) error
	// Acknowledge reports what the instance did with the state it received:
	// halt layers, bundle activations and the state version applied.
	Acknowledge(context.Context, *connect.Request[v1alpha1.AcknowledgeRequest]) (*connect.Response[v1alpha1.AcknowledgeResponse], error)
}

// NewGovernanceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGovernanceServiceHandler(svc GovernanceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	governanceServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_governance_proto.Services().ByName("GovernanceService").Methods()
	governanceServiceWatchHandler := connect.NewServerStreamHandler(
		GovernanceServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(governanceServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceAcknowledgeHandler := connect.NewUnaryHandler(
		GovernanceServiceAcknowledgeProcedure,
		svc.Acknowledge,
		connect.WithSchema(governanceServiceMethods.ByName("Acknowledge")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	return "/whitetower.module.v1alpha1.GovernanceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GovernanceServiceWatchProcedure:
			governanceServiceWatchHandler.ServeHTTP(w, r)
		case GovernanceServiceAcknowledgeProcedure:
			governanceServiceAcknowledgeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGovernanceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGovernanceServiceHandler struct{}

func (UnimplementedGovernanceServiceHandler) Watch(context.Context, *connect.Request[v1alpha1.WatchRequest], *connect.ServerStream[v1alpha1.WatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.GovernanceService.Watch is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) Acknowledge(context.Context, *connect.Request[v1alpha1.AcknowledgeRequest]) (*connect.Response[v1alpha1.AcknowledgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.GovernanceService.Acknowledge is not implemented"))
}
