// Placeholder that exercises the code generation pipeline (plan P0-01).
// The module contracts are defined by RFC-0001 (plan P0-03), which replaces this file.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whitetower/module/v1alpha1/meta.proto

package modulev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MetaServiceName is the fully-qualified name of the MetaService service.
	MetaServiceName = "whitetower.module.v1alpha1.MetaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MetaServiceGetServerInfoProcedure is the fully-qualified name of the MetaService's GetServerInfo
	// RPC.
	MetaServiceGetServerInfoProcedure = "/whitetower.module.v1alpha1.MetaService/GetServerInfo"
)

// MetaServiceClient is a client for the whitetower.module.v1alpha1.MetaService service.
type MetaServiceClient interface {
	// GetServerInfo returns the version of the server and the contract versions it supports.
	GetServerInfo(context.Context, *connect.Request[v1alpha1.GetServerInfoRequest]) (*connect.Response[v1alpha1.GetServerInfoResponse], error)
}

// NewMetaServiceClient constructs a client for the whitetower.module.v1alpha1.MetaService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMetaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MetaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	metaServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_meta_proto.Services().ByName("MetaService").Methods()
	return &metaServiceClient{
		getServerInfo: connect.NewClient[v1alpha1.GetServerInfoRequest, v1alpha1.GetServerInfoResponse](
			httpClient,
			baseURL+MetaServiceGetServerInfoProcedure,
			connect.WithSchema(metaServiceMethods.ByName("GetServerInfo")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// metaServiceClient implements MetaServiceClient.
type metaServiceClient struct {
	getServerInfo *connect.Client[v1alpha1.GetServerInfoRequest, v1alpha1.GetServerInfoResponse]
}

// GetServerInfo calls whitetower.module.v1alpha1.MetaService.GetServerInfo.
func (c *metaServiceClient) GetServerInfo(ctx context.Context, req *connect.Request[v1alpha1.GetServerInfoRequest]) (*connect.Response[v1alpha1.GetServerInfoResponse], error) {
	return c.getServerInfo.CallUnary(ctx, req)
}

// MetaServiceHandler is an implementation of the whitetower.module.v1alpha1.MetaService service.
type MetaServiceHandler interface {
	// GetServerInfo returns the version of the server and the contract versions it supports.
	GetServerInfo(context.Context, *connect.Request[v1alpha1.GetServerInfoRequest]) (*connect.Response[v1alpha1.GetServerInfoResponse], error)
}

// NewMetaServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMetaServiceHandler(svc MetaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	metaServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_meta_proto.Services().ByName("MetaService").Methods()
	metaServiceGetServerInfoHandler := connect.NewUnaryHandler(
		MetaServiceGetServerInfoProcedure,
		svc.GetServerInfo,
		connect.WithSchema(metaServiceMethods.ByName("GetServerInfo")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/whitetower.module.v1alpha1.MetaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MetaServiceGetServerInfoProcedure:
			metaServiceGetServerInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMetaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMetaServiceHandler struct{}

func (UnimplementedMetaServiceHandler) GetServerInfo(context.Context, *connect.Request[v1alpha1.GetServerInfoRequest]) (*connect.Response[v1alpha1.GetServerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.MetaService.GetServerInfo is not implemented"))
}
