// Module contracts v0.1 (RFC-0001): signed policy bundles.
// Normative text: docs/contracts/module-contract-v0.1.md, section 7.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whitetower/module/v1alpha1/policy.proto

package modulev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PolicyServiceName is the fully-qualified name of the PolicyService service.
	PolicyServiceName = "whitetower.module.v1alpha1.PolicyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PolicyServiceGetBundleProcedure is the fully-qualified name of the PolicyService's GetBundle RPC.
	PolicyServiceGetBundleProcedure = "/whitetower.module.v1alpha1.PolicyService/GetBundle"
	// PolicyServiceGetBundleKeysProcedure is the fully-qualified name of the PolicyService's
	// GetBundleKeys RPC.
	PolicyServiceGetBundleKeysProcedure = "/whitetower.module.v1alpha1.PolicyService/GetBundleKeys"
)

// PolicyServiceClient is a client for the whitetower.module.v1alpha1.PolicyService service.
type PolicyServiceClient interface {
	// GetBundle returns one version of an agent's bundle.
	GetBundle(context.Context, *connect.Request[v1alpha1.GetBundleRequest]) (*connect.Response[v1alpha1.GetBundleResponse], error)
	// GetBundleKeys returns the public keys the core signs bundles with,
	// including the next key during a rotation.
	GetBundleKeys(context.Context, *connect.Request[v1alpha1.GetBundleKeysRequest]) (*connect.Response[v1alpha1.GetBundleKeysResponse], error)
}

// NewPolicyServiceClient constructs a client for the whitetower.module.v1alpha1.PolicyService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPolicyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PolicyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	policyServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_policy_proto.Services().ByName("PolicyService").Methods()
	return &policyServiceClient{
		getBundle: connect.NewClient[v1alpha1.GetBundleRequest, v1alpha1.GetBundleResponse](
			httpClient,
			baseURL+PolicyServiceGetBundleProcedure,
			connect.WithSchema(policyServiceMethods.ByName("GetBundle")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getBundleKeys: connect.NewClient[v1alpha1.GetBundleKeysRequest, v1alpha1.GetBundleKeysResponse](
			httpClient,
			baseURL+PolicyServiceGetBundleKeysProcedure,
			connect.WithSchema(policyServiceMethods.ByName("GetBundleKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// policyServiceClient implements PolicyServiceClient.
type policyServiceClient struct {
	getBundle     *connect.Client[v1alpha1.GetBundleRequest, v1alpha1.GetBundleResponse]
	getBundleKeys *connect.Client[v1alpha1.GetBundleKeysRequest, v1alpha1.GetBundleKeysResponse]
}

// GetBundle calls whitetower.module.v1alpha1.PolicyService.GetBundle.
func (c *policyServiceClient) GetBundle(ctx context.Context, req *connect.Request[v1alpha1.GetBundleRequest]) (*connect.Response[v1alpha1.GetBundleResponse], error) {
	return c.getBundle.CallUnary(ctx, req)
}

// GetBundleKeys calls whitetower.module.v1alpha1.PolicyService.GetBundleKeys.
func (c *policyServiceClient) GetBundleKeys(ctx context.Context, req *connect.Request[v1alpha1.GetBundleKeysRequest]) (*connect.Response[v1alpha1.GetBundleKeysResponse], error) {
	return c.getBundleKeys.CallUnary(ctx, req)
}

// PolicyServiceHandler is an implementation of the whitetower.module.v1alpha1.PolicyService
// service.
type PolicyServiceHandler interface {
	// GetBundle returns one version of an agent's bundle.
	GetBundle(context.Context, *connect.Request[v1alpha1.GetBundleRequest]) (*connect.Response[v1alpha1.GetBundleResponse], error)
	// GetBundleKeys returns the public keys the core signs bundles with,
	// including the next key during a rotation.
	GetBundleKeys(context.Context, *connect.Request[v1alpha1.GetBundleKeysRequest]) (*connect.Response[v1alpha1.GetBundleKeysResponse], error)
}

// NewPolicyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPolicyServiceHandler(svc PolicyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	policyServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_policy_proto.Services().ByName("PolicyService").Methods()
	policyServiceGetBundleHandler := connect.NewUnaryHandler(
		PolicyServiceGetBundleProcedure,
		svc.GetBundle,
		connect.WithSchema(policyServiceMethods.ByName("GetBundle")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policyServiceGetBundleKeysHandler := connect.NewUnaryHandler(
		PolicyServiceGetBundleKeysProcedure,
		svc.GetBundleKeys,
		connect.WithSchema(policyServiceMethods.ByName("GetBundleKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/whitetower.module.v1alpha1.PolicyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PolicyServiceGetBundleProcedure:
			policyServiceGetBundleHandler.ServeHTTP(w, r)
		case PolicyServiceGetBundleKeysProcedure:
			policyServiceGetBundleKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPolicyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPolicyServiceHandler struct{}

func (UnimplementedPolicyServiceHandler) GetBundle(context.Context, *connect.Request[v1alpha1.GetBundleRequest]) (*connect.Response[v1alpha1.GetBundleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.PolicyService.GetBundle is not implemented"))
}

func (UnimplementedPolicyServiceHandler) GetBundleKeys(context.Context, *connect.Request[v1alpha1.GetBundleKeysRequest]) (*connect.Response[v1alpha1.GetBundleKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.PolicyService.GetBundleKeys is not implemented"))
}
