// Module contracts v0.1 (RFC-0001): instance registration.
// Normative text: docs/contracts/module-contract-v0.1.md, section 4.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whitetower/module/v1alpha1/registry.proto

package modulev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RegistryServiceName is the fully-qualified name of the RegistryService service.
	RegistryServiceName = "whitetower.module.v1alpha1.RegistryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RegistryServiceRegisterInstanceProcedure is the fully-qualified name of the RegistryService's
	// RegisterInstance RPC.
	RegistryServiceRegisterInstanceProcedure = "/whitetower.module.v1alpha1.RegistryService/RegisterInstance"
	// RegistryServiceHeartbeatProcedure is the fully-qualified name of the RegistryService's Heartbeat
	// RPC.
	RegistryServiceHeartbeatProcedure = "/whitetower.module.v1alpha1.RegistryService/Heartbeat"
	// RegistryServiceDeregisterInstanceProcedure is the fully-qualified name of the RegistryService's
	// DeregisterInstance RPC.
	RegistryServiceDeregisterInstanceProcedure = "/whitetower.module.v1alpha1.RegistryService/DeregisterInstance"
)

// RegistryServiceClient is a client for the whitetower.module.v1alpha1.RegistryService service.
type RegistryServiceClient interface {
	// RegisterInstance announces an instance and negotiates the contract version.
	// Registering again with the same module and instance key updates the
	// existing instance and returns the same instance ID.
	RegisterInstance(context.Context, *connect.Request[v1alpha1.RegisterInstanceRequest]) (*connect.Response[v1alpha1.RegisterInstanceResponse], error)
	// Heartbeat reports the instance's health and, when it changed, the set of
	// agents it serves.
	Heartbeat(context.Context, *connect.Request[v1alpha1.HeartbeatRequest]) (*connect.Response[v1alpha1.HeartbeatResponse], error)
	// DeregisterInstance tells the core that the instance is stopping on purpose,
	// so it is shown as disconnected rather than lost.
	DeregisterInstance(context.Context, *connect.Request[v1alpha1.DeregisterInstanceRequest]) (*connect.Response[v1alpha1.DeregisterInstanceResponse], error)
}

// NewRegistryServiceClient constructs a client for the whitetower.module.v1alpha1.RegistryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRegistryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RegistryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	registryServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_registry_proto.Services().ByName("RegistryService").Methods()
	return &registryServiceClient{
		registerInstance: connect.NewClient[v1alpha1.RegisterInstanceRequest, v1alpha1.RegisterInstanceResponse](
			httpClient,
			baseURL+RegistryServiceRegisterInstanceProcedure,
			connect.WithSchema(registryServiceMethods.ByName("RegisterInstance")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1alpha1.HeartbeatRequest, v1alpha1.HeartbeatResponse](
			httpClient,
			baseURL+RegistryServiceHeartbeatProcedure,
			connect.WithSchema(registryServiceMethods.ByName("Heartbeat")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		deregisterInstance: connect.NewClient[v1alpha1.DeregisterInstanceRequest, v1alpha1.DeregisterInstanceResponse](
			httpClient,
			baseURL+RegistryServiceDeregisterInstanceProcedure,
			connect.WithSchema(registryServiceMethods.ByName("DeregisterInstance")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
	}
}

// registryServiceClient implements RegistryServiceClient.
type registryServiceClient struct {
	registerInstance   *connect.Client[v1alpha1.RegisterInstanceRequest, v1alpha1.RegisterInstanceResponse]
	heartbeat          *connect.Client[v1alpha1.HeartbeatRequest, v1alpha1.HeartbeatResponse]
	deregisterInstance *connect.Client[v1alpha1.DeregisterInstanceRequest, v1alpha1.DeregisterInstanceResponse]
}

// RegisterInstance calls whitetower.module.v1alpha1.RegistryService.RegisterInstance.
func (c *registryServiceClient) RegisterInstance(ctx context.Context, req *connect.Request[v1alpha1.RegisterInstanceRequest]) (*connect.Response[v1alpha1.RegisterInstanceResponse], error) {
	return c.registerInstance.CallUnary(ctx, req)
}

// Heartbeat calls whitetower.module.v1alpha1.RegistryService.Heartbeat.
func (c *registryServiceClient) Heartbeat(ctx context.Context, req *connect.Request[v1alpha1.HeartbeatRequest]) (*connect.Response[v1alpha1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// DeregisterInstance calls whitetower.module.v1alpha1.RegistryService.DeregisterInstance.
func (c *registryServiceClient) DeregisterInstance(ctx context.Context, req *connect.Request[v1alpha1.DeregisterInstanceRequest]) (*connect.Response[v1alpha1.DeregisterInstanceResponse], error) {
	return c.deregisterInstance.CallUnary(ctx, req)
}

// RegistryServiceHandler is an implementation of the whitetower.module.v1alpha1.RegistryService
// service.
type RegistryServiceHandler interface {
	// RegisterInstance announces an instance and negotiates the contract version.
	// Registering again with the same module and instance key updates the
	// existing instance and returns the same instance ID.
	RegisterInstance(context.Context, *connect.Request[v1alpha1.RegisterInstanceRequest]) (*connect.Response[v1alpha1.RegisterInstanceResponse], error)
	// Heartbeat reports the instance's health and, when it changed, the set of
	// agents it serves.
	Heartbeat(context.Context, *connect.Request[v1alpha1.HeartbeatRequest]) (*connect.Response[v1alpha1.HeartbeatResponse], error)
	// DeregisterInstance tells the core that the instance is stopping on purpose,
	// so it is shown as disconnected rather than lost.
	DeregisterInstance(context.Context, *connect.Request[v1alpha1.DeregisterInstanceRequest]) (*connect.Response[v1alpha1.DeregisterInstanceResponse], error)
}

// NewRegistryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRegistryServiceHandler(svc RegistryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	registryServiceMethods := v1alpha1.File_whitetower_module_v1alpha1_registry_proto.Services().ByName("RegistryService").Methods()
	registryServiceRegisterInstanceHandler := connect.NewUnaryHandler(
		RegistryServiceRegisterInstanceProcedure,
		svc.RegisterInstance,
		connect.WithSchema(registryServiceMethods.ByName("RegisterInstance")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceHeartbeatHandler := connect.NewUnaryHandler(
		RegistryServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(registryServiceMethods.ByName("Heartbeat")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceDeregisterInstanceHandler := connect.NewUnaryHandler(
		RegistryServiceDeregisterInstanceProcedure,
		svc.DeregisterInstance,
		connect.WithSchema(registryServiceMethods.ByName("DeregisterInstance")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	return "/whitetower.module.v1alpha1.RegistryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RegistryServiceRegisterInstanceProcedure:
			registryServiceRegisterInstanceHandler.ServeHTTP(w, r)
		case RegistryServiceHeartbeatProcedure:
			registryServiceHeartbeatHandler.ServeHTTP(w, r)
		case RegistryServiceDeregisterInstanceProcedure:
			registryServiceDeregisterInstanceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRegistryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRegistryServiceHandler struct{}

func (UnimplementedRegistryServiceHandler) RegisterInstance(context.Context, *connect.Request[v1alpha1.RegisterInstanceRequest]) (*connect.Response[v1alpha1.RegisterInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.RegistryService.RegisterInstance is not implemented"))
}

func (UnimplementedRegistryServiceHandler) Heartbeat(context.Context, *connect.Request[v1alpha1.HeartbeatRequest]) (*connect.Response[v1alpha1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.RegistryService.Heartbeat is not implemented"))
}

func (UnimplementedRegistryServiceHandler) DeregisterInstance(context.Context, *connect.Request[v1alpha1.DeregisterInstanceRequest]) (*connect.Response[v1alpha1.DeregisterInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whitetower.module.v1alpha1.RegistryService.DeregisterInstance is not implemented"))
}
