-- +goose Up
-- White Tower database schema, version 0.1 (plan P0-02).
--
-- * Forward-only (requirement OPS-07): there is no Down migration.
-- * Runs as the migration role, which owns every object. The core connects
--   with a login role that is a member of whitetower_runtime, which only gets
--   the privileges granted at the end of this file.
-- * Identifiers are UUIDv7, generated by the application.
-- * Governance records are never deleted: they are retired or superseded.
-- * Audit and history tables are append-only: the runtime role may only
--   insert into them, and triggers reject UPDATE, DELETE and TRUNCATE for
--   everybody else too.
--
-- The model is explained in docs/architecture/domain-model.md and the agent
-- lifecycle in docs/architecture/lifecycle.md.

-- Roles and schema ---------------------------------------------------------

-- The group role is created here when the migration role may create roles;
-- otherwise a database administrator creates it beforehand.
-- +goose StatementBegin
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'whitetower_runtime') THEN
    CREATE ROLE whitetower_runtime NOLOGIN;
  END IF;
END
$$;
-- +goose StatementEnd

CREATE SCHEMA whitetower;
REVOKE ALL ON SCHEMA whitetower FROM PUBLIC;
GRANT USAGE ON SCHEMA whitetower TO whitetower_runtime;

-- Shared trigger functions -------------------------------------------------

-- +goose StatementBegin
CREATE FUNCTION whitetower.reject_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'whitetower: % on %.% is not allowed: the table is append-only',
    TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END
$$;
-- +goose StatementEnd

-- Every change that enforcement points must see takes a number from this
-- sequence, which gives all governance state changes a total order.
CREATE SEQUENCE whitetower.governance_state_version_seq AS bigint;

-- People and access ---------------------------------------------------------

CREATE TABLE whitetower.principals (
  id                       uuid PRIMARY KEY,
  kind                     text NOT NULL CHECK (kind IN ('human', 'service_account')),
  issuer                   text,
  subject                  text,
  display_name             text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 200),
  email                    text CHECK (email IS NULL OR length(email) <= 320),
  status                   text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  status_changed_at        timestamptz,
  status_reason            text,
  idp_groups               text[] NOT NULL DEFAULT '{}',
  last_login_at            timestamptz,
  responsible_principal_id uuid REFERENCES whitetower.principals (id),
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  version                  bigint NOT NULL DEFAULT 1,
  CONSTRAINT principals_human_identity
    CHECK (kind <> 'human' OR (issuer IS NOT NULL AND subject IS NOT NULL)),
  CONSTRAINT principals_service_account_responsible
    CHECK (kind <> 'service_account' OR responsible_principal_id IS NOT NULL)
);
CREATE UNIQUE INDEX principals_idp_identity ON whitetower.principals (issuer, subject) WHERE kind = 'human';

CREATE TABLE whitetower.role_bindings (
  id           uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES whitetower.principals (id),
  role         text NOT NULL
               CHECK (role IN ('steering', 'advisory', 'owner', 'user', 'operator', 'auditor', 'admin')),
  reason       text NOT NULL CHECK (length(reason) > 0),
  granted_by   uuid NOT NULL REFERENCES whitetower.principals (id),
  granted_at   timestamptz NOT NULL DEFAULT now(),
  revoked_by   uuid REFERENCES whitetower.principals (id),
  revoked_at   timestamptz,
  CONSTRAINT role_bindings_revocation_complete CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
);
CREATE UNIQUE INDEX role_bindings_one_active ON whitetower.role_bindings (principal_id, role)
  WHERE revoked_at IS NULL;

CREATE TABLE whitetower.sessions (
  id_hash             bytea PRIMARY KEY CHECK (octet_length(id_hash) = 32),
  principal_id        uuid NOT NULL REFERENCES whitetower.principals (id),
  method              text NOT NULL CHECK (method IN ('oidc', 'cli', 'breakglass')),
  roles               text[] NOT NULL,
  csrf_token_hash     bytea NOT NULL CHECK (octet_length(csrf_token_hash) = 32),
  created_at          timestamptz NOT NULL DEFAULT now(),
  last_seen_at        timestamptz NOT NULL DEFAULT now(),
  idle_expires_at     timestamptz NOT NULL,
  absolute_expires_at timestamptz NOT NULL,
  revoked_at          timestamptz
);
CREATE INDEX sessions_by_principal ON whitetower.sessions (principal_id) WHERE revoked_at IS NULL;

CREATE TABLE whitetower.api_tokens (
  id           uuid PRIMARY KEY,
  principal_id uuid NOT NULL REFERENCES whitetower.principals (id),
  name         text NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
  token_prefix text NOT NULL,
  token_hash   bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  scopes       text[] NOT NULL,
  created_by   uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  CONSTRAINT api_tokens_expire_after_creation CHECK (expires_at > created_at)
);

-- Inventory -------------------------------------------------------------------

CREATE TABLE whitetower.use_cases (
  id                     uuid PRIMARY KEY,
  title                  text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
  description            text NOT NULL,
  business_justification text NOT NULL,
  data_categories        text[] NOT NULL DEFAULT '{}',
  affected_persons       text,
  ai_act_classification  text NOT NULL DEFAULT 'not_assessed'
                         CHECK (ai_act_classification IN ('prohibited', 'high_risk', 'limited', 'minimal', 'not_assessed')),
  status                 text NOT NULL DEFAULT 'draft'
                         CHECK (status IN ('draft', 'submitted', 'changes_requested', 'validated', 'rejected')),
  conditions             text,
  created_by             uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  version                bigint NOT NULL DEFAULT 1
);

CREATE TABLE whitetower.agents (
  id                    uuid PRIMARY KEY,
  slug                  text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'),
  name                  text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  description           text NOT NULL,
  kind                  text NOT NULL CHECK (kind IN ('in_house', 'third_party')),
  source                text NOT NULL DEFAULT 'registered' CHECK (source IN ('registered', 'imported', 'discovered')),
  vendor                text,
  framework             text,
  deployment_location   text,
  environments          text[] NOT NULL DEFAULT '{}',
  risk_tier             text NOT NULL CHECK (risk_tier IN ('low', 'medium', 'high', 'critical')),
  ai_act_classification text NOT NULL DEFAULT 'not_assessed'
                        CHECK (ai_act_classification IN ('prohibited', 'high_risk', 'limited', 'minimal', 'not_assessed')),
  data_categories       text[] NOT NULL DEFAULT '{}',
  use_case_id           uuid NOT NULL REFERENCES whitetower.use_cases (id),
  lifecycle_state       text NOT NULL DEFAULT 'draft'
                        CHECK (lifecycle_state IN ('draft', 'proposed', 'validated', 'ready', 'active', 'suspended', 'retired', 'rejected')),
  suspended_from        text CHECK (suspended_from IN ('validated', 'ready', 'active')),
  suspension_reason     text CHECK (suspension_reason IN ('manual', 'owner_inactive', 'review_overdue', 'halt')),
  suspended_at          timestamptz,
  harness               jsonb CHECK (harness IS NULL OR jsonb_typeof(harness) = 'object'),
  halt_mode             text NOT NULL DEFAULT 'interrupt' CHECK (halt_mode IN ('block', 'interrupt', 'terminate')),
  drill_eligible        boolean NOT NULL DEFAULT false,
  labels                jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(labels) = 'object'),
  activated_at          timestamptz,
  retired_at            timestamptz,
  created_by            uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  version               bigint NOT NULL DEFAULT 1,
  CONSTRAINT agents_suspension_recorded CHECK (
    (lifecycle_state = 'suspended')
    = (suspended_from IS NOT NULL AND suspension_reason IS NOT NULL AND suspended_at IS NOT NULL)),
  CONSTRAINT agents_retirement_recorded CHECK ((lifecycle_state = 'retired') = (retired_at IS NOT NULL)),
  CONSTRAINT agents_ready_needs_harness CHECK (lifecycle_state NOT IN ('ready', 'active') OR harness IS NOT NULL)
);
CREATE INDEX agents_by_state ON whitetower.agents (lifecycle_state);
CREATE INDEX agents_by_use_case ON whitetower.agents (use_case_id);
CREATE INDEX agents_by_labels ON whitetower.agents USING gin (labels);

CREATE TABLE whitetower.use_case_decisions (
  id          uuid PRIMARY KEY,
  use_case_id uuid NOT NULL REFERENCES whitetower.use_cases (id),
  agent_id    uuid REFERENCES whitetower.agents (id),
  decision    text NOT NULL CHECK (decision IN ('validated', 'rejected', 'changes_requested')),
  comment     text NOT NULL CHECK (length(comment) > 0),
  decided_by  uuid NOT NULL REFERENCES whitetower.principals (id),
  decided_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE whitetower.agent_owners (
  id           uuid PRIMARY KEY,
  agent_id     uuid NOT NULL REFERENCES whitetower.agents (id),
  principal_id uuid NOT NULL REFERENCES whitetower.principals (id),
  role         text NOT NULL CHECK (role IN ('primary', 'delegate')),
  assigned_by  uuid NOT NULL REFERENCES whitetower.principals (id),
  assigned_at  timestamptz NOT NULL DEFAULT now(),
  ended_by     uuid REFERENCES whitetower.principals (id),
  ended_at     timestamptz,
  end_reason   text,
  CONSTRAINT agent_owners_end_recorded CHECK ((ended_at IS NULL) = (end_reason IS NULL))
);
CREATE UNIQUE INDEX agent_owners_one_primary ON whitetower.agent_owners (agent_id)
  WHERE role = 'primary' AND ended_at IS NULL;
CREATE UNIQUE INDEX agent_owners_one_assignment ON whitetower.agent_owners (agent_id, principal_id)
  WHERE ended_at IS NULL;
CREATE INDEX agent_owners_by_principal ON whitetower.agent_owners (principal_id) WHERE ended_at IS NULL;

CREATE TABLE whitetower.ownership_transfers (
  id                uuid PRIMARY KEY,
  agent_id          uuid NOT NULL REFERENCES whitetower.agents (id),
  from_principal_id uuid NOT NULL REFERENCES whitetower.principals (id),
  to_principal_id   uuid NOT NULL REFERENCES whitetower.principals (id),
  requested_by      uuid NOT NULL REFERENCES whitetower.principals (id),
  requested_at      timestamptz NOT NULL DEFAULT now(),
  status            text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled', 'expired')),
  decided_at        timestamptz,
  CONSTRAINT ownership_transfers_to_someone_else CHECK (from_principal_id <> to_principal_id)
);
CREATE UNIQUE INDEX ownership_transfers_one_pending ON whitetower.ownership_transfers (agent_id)
  WHERE status = 'pending';

CREATE TABLE whitetower.lifecycle_transitions (
  id            uuid PRIMARY KEY,
  agent_id      uuid NOT NULL REFERENCES whitetower.agents (id),
  action        text NOT NULL,
  from_state    text,
  to_state      text NOT NULL,
  actor_type    text NOT NULL CHECK (actor_type IN ('human', 'system', 'breakglass')),
  actor_id      uuid REFERENCES whitetower.principals (id),
  reason        text,
  comment       text,
  state_version bigint NOT NULL,
  occurred_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lifecycle_transitions_actor_known CHECK (actor_type = 'system' OR actor_id IS NOT NULL)
);
CREATE INDEX lifecycle_transitions_by_agent ON whitetower.lifecycle_transitions (agent_id, occurred_at);

CREATE TABLE whitetower.reviews (
  id               uuid PRIMARY KEY,
  agent_id         uuid NOT NULL REFERENCES whitetower.agents (id),
  due_at           timestamptz NOT NULL,
  grace_ends_at    timestamptz NOT NULL,
  status           text NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled', 'awaiting_signoff', 'completed', 'cancelled')),
  attestation      jsonb CHECK (attestation IS NULL OR jsonb_typeof(attestation) = 'object'),
  completed_by     uuid REFERENCES whitetower.principals (id),
  completed_at     timestamptz,
  signoff_required boolean NOT NULL,
  signed_off_by    uuid REFERENCES whitetower.principals (id),
  signed_off_at    timestamptz,
  last_reminder_at timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  version          bigint NOT NULL DEFAULT 1,
  CONSTRAINT reviews_grace_after_due CHECK (grace_ends_at >= due_at),
  CONSTRAINT reviews_signoff_by_someone_else CHECK (signed_off_by IS NULL OR signed_off_by <> completed_by)
);
CREATE UNIQUE INDEX reviews_one_open ON whitetower.reviews (agent_id)
  WHERE status IN ('scheduled', 'awaiting_signoff');

-- Machine identity ----------------------------------------------------------------

CREATE TABLE whitetower.signing_keys (
  key_id       text PRIMARY KEY,
  purpose      text NOT NULL CHECK (purpose IN ('token', 'bundle', 'checkpoint')),
  algorithm    text NOT NULL CHECK (algorithm IN ('ES256', 'EdDSA')),
  -- Public halves only: private keys never enter the database.
  public_jwk   jsonb NOT NULL CHECK (jsonb_typeof(public_jwk) = 'object' AND NOT public_jwk ? 'd'),
  status       text NOT NULL CHECK (status IN ('next', 'active', 'retired')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  retired_at   timestamptz
);
CREATE UNIQUE INDEX signing_keys_one_active ON whitetower.signing_keys (purpose) WHERE status = 'active';

CREATE TABLE whitetower.modules (
  id                uuid PRIMARY KEY,
  slug              text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'),
  name              text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  vendor            text NOT NULL,
  module_version    text NOT NULL,
  manifest          jsonb NOT NULL CHECK (jsonb_typeof(manifest) = 'object'),
  manifest_sha256   bytea NOT NULL CHECK (octet_length(manifest_sha256) = 32),
  capabilities      text[] NOT NULL,
  contract_versions text[] NOT NULL,
  status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'revoked')),
  registered_by     uuid NOT NULL REFERENCES whitetower.principals (id),
  registered_at     timestamptz NOT NULL DEFAULT now(),
  approved_by       uuid REFERENCES whitetower.principals (id),
  approved_at       timestamptz,
  revoked_by        uuid REFERENCES whitetower.principals (id),
  revoked_at        timestamptz,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  version           bigint NOT NULL DEFAULT 1,
  CONSTRAINT modules_approval_recorded CHECK ((approved_at IS NULL) = (approved_by IS NULL)),
  CONSTRAINT modules_revocation_recorded CHECK ((status = 'revoked') = (revoked_at IS NOT NULL))
);

CREATE TABLE whitetower.machine_credentials (
  id                uuid PRIMARY KEY,
  agent_id          uuid REFERENCES whitetower.agents (id),
  module_id         uuid REFERENCES whitetower.modules (id),
  key_id            text NOT NULL,
  -- Public keys only (requirement AID-02): a JWK with a private member is refused.
  public_jwk        jsonb NOT NULL CHECK (jsonb_typeof(public_jwk) = 'object' AND NOT public_jwk ? 'd'),
  algorithm         text NOT NULL CHECK (algorithm IN ('ES256', 'EdDSA')),
  thumbprint        text NOT NULL UNIQUE,
  environment       text CHECK (environment IN ('production', 'non_production')),
  status            text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_by        uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at        timestamptz NOT NULL DEFAULT now(),
  expires_at        timestamptz,
  revoked_by        uuid REFERENCES whitetower.principals (id),
  revoked_at        timestamptz,
  revocation_reason text,
  last_used_at      timestamptz,
  CONSTRAINT machine_credentials_one_holder CHECK ((agent_id IS NULL) <> (module_id IS NULL)),
  CONSTRAINT machine_credentials_agent_environment CHECK (agent_id IS NULL OR environment IS NOT NULL),
  CONSTRAINT machine_credentials_revocation_recorded CHECK ((status = 'revoked') = (revoked_at IS NOT NULL))
);
CREATE UNIQUE INDEX machine_credentials_key_id ON whitetower.machine_credentials (coalesce(agent_id, module_id), key_id);

CREATE TABLE whitetower.workload_issuers (
  id          uuid PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  issuer      text NOT NULL UNIQUE,
  -- Static keys for clusters the core cannot reach; NULL means OIDC discovery.
  jwks        jsonb CHECK (jwks IS NULL OR jsonb_typeof(jwks) = 'object'),
  created_by  uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  disabled_at timestamptz
);

CREATE TABLE whitetower.workload_identity_bindings (
  id          uuid PRIMARY KEY,
  issuer_id   uuid NOT NULL REFERENCES whitetower.workload_issuers (id),
  subject     text NOT NULL,
  agent_id    uuid NOT NULL REFERENCES whitetower.agents (id),
  environment text NOT NULL CHECK (environment IN ('production', 'non_production')),
  created_by  uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  revoked_at  timestamptz
);
CREATE UNIQUE INDEX workload_identity_bindings_active ON whitetower.workload_identity_bindings (issuer_id, subject)
  WHERE revoked_at IS NULL;

-- Replay protection for client assertions (RFC 7523); rows expire within minutes.
CREATE TABLE whitetower.used_assertions (
  client_id  text NOT NULL,
  jti        text NOT NULL,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (client_id, jti)
);
CREATE INDEX used_assertions_by_expiry ON whitetower.used_assertions (expires_at);

-- Policies ----------------------------------------------------------------------

CREATE TABLE whitetower.policies (
  id          uuid PRIMARY KEY,
  name        text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  description text NOT NULL DEFAULT '',
  scope       text NOT NULL CHECK (scope IN ('global', 'agent')),
  agent_id    uuid REFERENCES whitetower.agents (id),
  language    text NOT NULL CHECK (language IN ('cedar', 'rego')),
  created_by  uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  retired_at  timestamptz,
  CONSTRAINT policies_agent_scope CHECK ((scope = 'agent') = (agent_id IS NOT NULL))
);
CREATE INDEX policies_by_agent ON whitetower.policies (agent_id) WHERE agent_id IS NOT NULL;

CREATE TABLE whitetower.policy_versions (
  id             uuid PRIMARY KEY,
  policy_id      uuid NOT NULL REFERENCES whitetower.policies (id),
  version_number integer NOT NULL CHECK (version_number > 0),
  content        text NOT NULL,
  content_sha256 bytea NOT NULL CHECK (octet_length(content_sha256) = 32),
  tests          text,
  change_note    text NOT NULL DEFAULT '',
  status         text NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft', 'submitted', 'approved', 'active', 'superseded', 'rejected', 'withdrawn')),
  validation     jsonb,
  author_id      uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at     timestamptz NOT NULL DEFAULT now(),
  submitted_at   timestamptz,
  activated_at   timestamptz,
  superseded_at  timestamptz,
  UNIQUE (policy_id, version_number)
);
CREATE UNIQUE INDEX policy_versions_one_active ON whitetower.policy_versions (policy_id) WHERE status = 'active';

-- +goose StatementBegin
CREATE FUNCTION whitetower.keep_submitted_policy_content() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status <> 'draft' AND (
       NEW.content IS DISTINCT FROM OLD.content
    OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
    OR NEW.tests IS DISTINCT FROM OLD.tests
    OR NEW.author_id IS DISTINCT FROM OLD.author_id) THEN
    RAISE EXCEPTION 'whitetower: policy version % was submitted, so its content can no longer change', OLD.id
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;
-- +goose StatementEnd
CREATE TRIGGER policy_versions_keep_submitted_content BEFORE UPDATE ON whitetower.policy_versions
  FOR EACH ROW EXECUTE FUNCTION whitetower.keep_submitted_policy_content();

CREATE TABLE whitetower.policy_approvals (
  id                uuid PRIMARY KEY,
  policy_version_id uuid NOT NULL REFERENCES whitetower.policy_versions (id),
  approver_id       uuid NOT NULL REFERENCES whitetower.principals (id),
  approver_role     text NOT NULL CHECK (approver_role IN ('steering', 'advisory')),
  decision          text NOT NULL CHECK (decision IN ('approved', 'rejected')),
  comment           text,
  decided_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (policy_version_id, approver_id),
  CONSTRAINT policy_approvals_rejection_explained
    CHECK (decision <> 'rejected' OR (comment IS NOT NULL AND length(comment) > 0))
);

-- Separation of duties (requirement HUM-04), enforced again by the database.
-- +goose StatementBegin
CREATE FUNCTION whitetower.reject_self_approval() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT FROM whitetower.policy_versions v
             WHERE v.id = NEW.policy_version_id AND v.author_id = NEW.approver_id) THEN
    RAISE EXCEPTION 'whitetower: the author of a policy version cannot decide on it'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NEW;
END
$$;
-- +goose StatementEnd
CREATE TRIGGER policy_approvals_not_by_author BEFORE INSERT ON whitetower.policy_approvals
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_self_approval();

CREATE TABLE whitetower.policy_bundles (
  id             uuid PRIMARY KEY,
  agent_id       uuid NOT NULL REFERENCES whitetower.agents (id),
  bundle_version bigint NOT NULL CHECK (bundle_version > 0),
  content_sha256 bytea NOT NULL CHECK (octet_length(content_sha256) = 32),
  manifest       jsonb NOT NULL CHECK (jsonb_typeof(manifest) = 'object'),
  content        bytea NOT NULL,
  signature      text NOT NULL,
  key_id         text NOT NULL REFERENCES whitetower.signing_keys (key_id),
  reason         text NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (agent_id, bundle_version)
);

-- Runtime: modules, instances and governance state ---------------------------------

-- Which agents a standalone module may serve: named agents, or every agent, as the
-- network quarantine module of a cluster does (KIL-10).
CREATE TABLE whitetower.module_agent_bindings (
  id         uuid PRIMARY KEY,
  module_id  uuid NOT NULL REFERENCES whitetower.modules (id),
  scope      text NOT NULL DEFAULT 'agent' CHECK (scope IN ('agent', 'all')),
  agent_id   uuid REFERENCES whitetower.agents (id),
  created_by uuid NOT NULL REFERENCES whitetower.principals (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  CONSTRAINT module_agent_bindings_target CHECK ((scope = 'agent') = (agent_id IS NOT NULL))
);
CREATE UNIQUE INDEX module_agent_bindings_active ON whitetower.module_agent_bindings (module_id, agent_id)
  WHERE removed_at IS NULL AND scope = 'agent';
CREATE UNIQUE INDEX module_agent_bindings_all_active ON whitetower.module_agent_bindings (module_id)
  WHERE removed_at IS NULL AND scope = 'all';

CREATE TABLE whitetower.module_instances (
  id                uuid PRIMARY KEY,
  module_id         uuid NOT NULL REFERENCES whitetower.modules (id),
  instance_key      text NOT NULL,
  -- An enforcement point embedded in an agent authenticates as that agent.
  identity_kind     text NOT NULL CHECK (identity_kind IN ('agent', 'module')),
  identity_agent_id uuid REFERENCES whitetower.agents (id),
  module_version    text NOT NULL,
  contract_version  text NOT NULL,
  host              text,
  status            text NOT NULL CHECK (status IN ('connected', 'disconnected', 'lost')),
  core_replica      text,
  lease_ttl_seconds integer NOT NULL CHECK (lease_ttl_seconds BETWEEN 10 AND 300),
  connected_at      timestamptz NOT NULL,
  last_seen_at      timestamptz NOT NULL,
  disconnected_at   timestamptz,
  UNIQUE (module_id, instance_key),
  CONSTRAINT module_instances_identity CHECK ((identity_kind = 'agent') = (identity_agent_id IS NOT NULL))
);

CREATE TABLE whitetower.instance_agents (
  instance_id            uuid NOT NULL REFERENCES whitetower.module_instances (id),
  agent_id               uuid NOT NULL REFERENCES whitetower.agents (id),
  active_bundle_version  bigint,
  bundle_activated_at    timestamptz,
  observed_state_version bigint,
  updated_at             timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (instance_id, agent_id)
);
CREATE INDEX instance_agents_by_agent ON whitetower.instance_agents (agent_id);

-- What the core publishes to enforcement points for each agent (ADR-0005).
-- Fleet-wide halts live in fleet_state, so a fleet halt changes one row.
CREATE TABLE whitetower.governance_state (
  agent_id          uuid PRIMARY KEY REFERENCES whitetower.agents (id),
  lifecycle_state   text NOT NULL,
  run_state         text NOT NULL DEFAULT 'running' CHECK (run_state IN ('running', 'halted')),
  agent_halt_ids    uuid[] NOT NULL DEFAULT '{}',
  bundle_id         uuid REFERENCES whitetower.policy_bundles (id),
  lease_ttl_seconds integer NOT NULL CHECK (lease_ttl_seconds BETWEEN 10 AND 300),
  labels            jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(labels) = 'object'),
  state_version     bigint NOT NULL,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT governance_state_halts CHECK ((run_state = 'halted') = (cardinality(agent_halt_ids) > 0))
);
CREATE INDEX governance_state_by_version ON whitetower.governance_state (state_version);

CREATE TABLE whitetower.fleet_state (
  id            smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  run_state     text NOT NULL DEFAULT 'running' CHECK (run_state IN ('running', 'halted')),
  halt_ids      uuid[] NOT NULL DEFAULT '{}',
  state_version bigint NOT NULL,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fleet_state_halts CHECK ((run_state = 'halted') = (cardinality(halt_ids) > 0))
);
INSERT INTO whitetower.fleet_state (id, state_version)
  VALUES (1, nextval('whitetower.governance_state_version_seq'));

-- Kill switch ----------------------------------------------------------------------

CREATE TABLE whitetower.halts (
  id              uuid PRIMARY KEY,
  scope           text NOT NULL CHECK (scope IN ('agent', 'fleet', 'selector')),
  agent_id        uuid REFERENCES whitetower.agents (id),
  selector        jsonb CHECK (selector IS NULL OR jsonb_typeof(selector) = 'object'),
  reason          text NOT NULL CHECK (length(reason) > 0),
  drill           boolean NOT NULL DEFAULT false,
  issued_by_type  text NOT NULL CHECK (issued_by_type IN ('human', 'breakglass', 'system')),
  issued_by       uuid REFERENCES whitetower.principals (id),
  issued_at       timestamptz NOT NULL DEFAULT now(),
  idempotency_key text UNIQUE,
  status          text NOT NULL DEFAULT 'propagating'
                  CHECK (status IN ('propagating', 'confirmed', 'partially_confirmed', 'unconfirmed', 'released')),
  released_at     timestamptz,
  state_version   bigint NOT NULL,
  CONSTRAINT halts_target CHECK (
       (scope = 'agent'    AND agent_id IS NOT NULL AND selector IS NULL)
    OR (scope = 'fleet'    AND agent_id IS NULL     AND selector IS NULL)
    OR (scope = 'selector' AND agent_id IS NULL     AND selector IS NOT NULL)),
  CONSTRAINT halts_drills_target_one_agent CHECK (NOT drill OR scope = 'agent'),
  CONSTRAINT halts_issuer_known CHECK (issued_by_type = 'system' OR issued_by IS NOT NULL),
  CONSTRAINT halts_release_recorded CHECK ((status = 'released') = (released_at IS NOT NULL))
);
CREATE INDEX halts_active ON whitetower.halts (scope, agent_id) WHERE status <> 'released';

CREATE TABLE whitetower.halt_acks (
  halt_id                uuid NOT NULL REFERENCES whitetower.halts (id),
  instance_id            uuid NOT NULL REFERENCES whitetower.module_instances (id),
  agent_id               uuid NOT NULL REFERENCES whitetower.agents (id),
  expected               boolean NOT NULL,
  gate_closed_at         timestamptz,
  interrupted_at         timestamptz,
  interruption_confirmed boolean,
  terminated_at          timestamptz,
  -- Network quarantine (KIL-10), reported by runtime-control modules.
  quarantined_at         timestamptz,
  quarantined_workloads  integer CHECK (quarantined_workloads IS NULL OR quarantined_workloads >= 0),
  acknowledged_at        timestamptz,
  error                  text,
  PRIMARY KEY (halt_id, instance_id, agent_id)
);

CREATE TABLE whitetower.halt_release_requests (
  id           uuid PRIMARY KEY,
  halt_id      uuid NOT NULL REFERENCES whitetower.halts (id),
  reason       text NOT NULL CHECK (length(reason) > 0),
  requested_by uuid NOT NULL REFERENCES whitetower.principals (id),
  requested_at timestamptz NOT NULL DEFAULT now(),
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  decided_by   uuid REFERENCES whitetower.principals (id),
  decided_at   timestamptz,
  comment      text,
  -- Two different people (requirement KIL-05).
  CONSTRAINT halt_release_two_people CHECK (decided_by IS NULL OR decided_by <> requested_by),
  CONSTRAINT halt_release_decision_recorded
    CHECK ((status IN ('approved', 'rejected')) = (decided_by IS NOT NULL AND decided_at IS NOT NULL))
);
CREATE UNIQUE INDEX halt_release_one_pending ON whitetower.halt_release_requests (halt_id) WHERE status = 'pending';

-- A halt is released only through an approved request, except drills, which
-- the system releases itself once confirmed.
-- +goose StatementBegin
CREATE FUNCTION whitetower.release_needs_approval() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'released' AND OLD.status <> 'released' AND NOT NEW.drill AND NOT EXISTS (
       SELECT FROM whitetower.halt_release_requests r
       WHERE r.halt_id = NEW.id AND r.status = 'approved') THEN
    RAISE EXCEPTION 'whitetower: halt % can only be released through an approved release request', NEW.id
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF OLD.status = 'released' AND NEW.status <> 'released' THEN
    RAISE EXCEPTION 'whitetower: halt % was released and cannot be reopened; issue a new halt', NEW.id
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END
$$;
-- +goose StatementEnd
CREATE TRIGGER halts_release_needs_approval BEFORE UPDATE ON whitetower.halts
  FOR EACH ROW EXECUTE FUNCTION whitetower.release_needs_approval();

-- Audit (ADR-0006) -----------------------------------------------------------------

-- Events, partitioned by month of ingestion. The canonical JSON (RFC 8785)
-- is the leaf of the Merkle tree; the other columns are extracted from it for
-- queries and must match it.
CREATE TABLE whitetower.audit_events (
  id               uuid NOT NULL,
  ingested_at      timestamptz NOT NULL DEFAULT now(),
  source           text NOT NULL,
  event_id         text NOT NULL,
  source_seq       bigint,
  type             text NOT NULL,
  event_time       timestamptz NOT NULL,
  subject_agent_id uuid,
  actor_type       text NOT NULL CHECK (actor_type IN ('human', 'agent', 'module', 'system', 'breakglass')),
  actor_id         text,
  action           text NOT NULL,
  outcome          text CHECK (outcome IN ('success', 'failure', 'allow', 'deny', 'blocked', 'error')),
  reason           text,
  request_id       text,
  trace_id         text,
  canonical        bytea NOT NULL,
  PRIMARY KEY (ingested_at, id)
) PARTITION BY RANGE (ingested_at);
CREATE INDEX audit_events_by_id ON whitetower.audit_events (id);
CREATE INDEX audit_events_by_agent ON whitetower.audit_events (subject_agent_id, ingested_at);
CREATE INDEX audit_events_by_type ON whitetower.audit_events (type, ingested_at);
CREATE INDEX audit_events_by_actor ON whitetower.audit_events (actor_id, ingested_at);

-- De-duplication of events sent more than once (at-least-once delivery),
-- partitioned like the events so retention drops both together.
CREATE TABLE whitetower.audit_event_ids (
  source       text NOT NULL,
  event_id     text NOT NULL,
  ingest_month date NOT NULL CHECK (extract(day FROM ingest_month) = 1),
  audit_id     uuid NOT NULL,
  PRIMARY KEY (source, event_id, ingest_month)
) PARTITION BY RANGE (ingest_month);

CREATE TABLE whitetower.audit_source_sequences (
  source       text PRIMARY KEY,
  last_seq     bigint NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE whitetower.audit_leaves (
  leaf_index  bigint PRIMARY KEY CHECK (leaf_index >= 0),
  audit_id    uuid NOT NULL UNIQUE,
  ingested_at timestamptz NOT NULL,
  leaf_hash   bytea NOT NULL CHECK (octet_length(leaf_hash) = 32),
  sealed_at   timestamptz NOT NULL DEFAULT now()
);

-- Intermediate hashes of the Merkle tree, indexed as golang.org/x/mod/sumdb/tlog stores them.
CREATE TABLE whitetower.audit_tree_hashes (
  hash_index bigint PRIMARY KEY CHECK (hash_index >= 0),
  hash       bytea NOT NULL CHECK (octet_length(hash) = 32)
);

CREATE TABLE whitetower.audit_checkpoints (
  tree_size   bigint PRIMARY KEY CHECK (tree_size > 0),
  root_hash   bytea NOT NULL CHECK (octet_length(root_hash) = 32),
  signed_note text NOT NULL,
  key_id      text NOT NULL REFERENCES whitetower.signing_keys (key_id),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE whitetower.audit_export_cursors (
  sink              text PRIMARY KEY,
  last_leaf_index   bigint NOT NULL DEFAULT -1,
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- Creates the monthly partitions of the audit tables for the current month and
-- the next months_ahead months. Called by the migration and by a job; runs
-- with the owner's rights, so the runtime role needs no DDL privileges.
-- +goose StatementBegin
CREATE FUNCTION whitetower.ensure_audit_partitions(months_ahead integer DEFAULT 3) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  first_month date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
  month_start date;
  month_end   date;
  suffix      text;
BEGIN
  IF months_ahead < 0 OR months_ahead > 24 THEN
    RAISE EXCEPTION 'whitetower: months_ahead must be between 0 and 24';
  END IF;
  FOR i IN 0..months_ahead LOOP
    month_start := (first_month + make_interval(months => i))::date;
    month_end   := (first_month + make_interval(months => i + 1))::date;
    suffix      := to_char(month_start, 'YYYY_MM');
    IF to_regclass('whitetower.audit_events_' || suffix) IS NULL THEN
      EXECUTE format(
        'CREATE TABLE whitetower.%I PARTITION OF whitetower.audit_events FOR VALUES FROM (%L) TO (%L)',
        'audit_events_' || suffix,
        month_start::timestamp AT TIME ZONE 'UTC',
        month_end::timestamp AT TIME ZONE 'UTC');
    END IF;
    IF to_regclass('whitetower.audit_event_ids_' || suffix) IS NULL THEN
      EXECUTE format(
        'CREATE TABLE whitetower.%I PARTITION OF whitetower.audit_event_ids FOR VALUES FROM (%L) TO (%L)',
        'audit_event_ids_' || suffix, month_start, month_end);
    END IF;
  END LOOP;
END
$$;
-- +goose StatementEnd
REVOKE ALL ON FUNCTION whitetower.ensure_audit_partitions(integer) FROM PUBLIC;
SELECT whitetower.ensure_audit_partitions(3);

-- Platform ---------------------------------------------------------------------------

CREATE TABLE whitetower.settings (
  key        text PRIMARY KEY CHECK (key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$'),
  value      jsonb NOT NULL,
  updated_by uuid REFERENCES whitetower.principals (id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version    bigint NOT NULL DEFAULT 1
);
INSERT INTO whitetower.settings (key, value) VALUES
  ('lifecycle.review_interval_days', '{"low": 365, "medium": 365, "high": 180, "critical": 90}'),
  ('lifecycle.review_grace_days', '14'),
  ('lifecycle.review_reminder_days', '[30, 7, 1]'),
  ('lifecycle.review_signoff_risk_tiers', '["high", "critical"]'),
  ('killswitch.lease_ttl_seconds', '{"low": 60, "medium": 60, "high": 30, "critical": 15}'),
  ('killswitch.unconfirmed_after_seconds', '10'),
  ('audit.retention_months', '6'),
  ('inventory.data_categories', '["public_data", "internal_documents", "customer_data", "employee_data", "personal_data", "special_category_data", "financial_data", "health_data", "source_code", "credentials"]');

CREATE TABLE whitetower.outbox (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  topic        text NOT NULL,
  payload      jsonb NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);
CREATE INDEX outbox_unpublished ON whitetower.outbox (id) WHERE published_at IS NULL;

CREATE TABLE whitetower.job_state (
  name             text PRIMARY KEY,
  last_started_at  timestamptz,
  last_finished_at timestamptz,
  last_status      text CHECK (last_status IN ('success', 'failure')),
  last_error       text,
  runner           text
);

CREATE TABLE whitetower.inbox_items (
  id           uuid PRIMARY KEY,
  principal_id uuid REFERENCES whitetower.principals (id),
  role         text CHECK (role IN ('steering', 'advisory', 'owner', 'user', 'operator', 'auditor', 'admin')),
  kind         text NOT NULL CHECK (kind IN (
                 'use_case_validation', 'policy_approval', 'review_due', 'review_signoff',
                 'halt_release', 'ownership_transfer', 'module_approval')),
  subject_type text NOT NULL,
  subject_id   uuid NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  resolved_at  timestamptz,
  CONSTRAINT inbox_items_one_recipient CHECK ((principal_id IS NULL) <> (role IS NULL))
);
CREATE INDEX inbox_items_open_by_principal ON whitetower.inbox_items (principal_id, created_at)
  WHERE resolved_at IS NULL;
CREATE INDEX inbox_items_open_by_role ON whitetower.inbox_items (role, created_at)
  WHERE resolved_at IS NULL;

-- Append-only tables ------------------------------------------------------------------

CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON whitetower.audit_events
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_events_no_truncate BEFORE TRUNCATE ON whitetower.audit_events
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_event_ids_append_only BEFORE UPDATE OR DELETE ON whitetower.audit_event_ids
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_event_ids_no_truncate BEFORE TRUNCATE ON whitetower.audit_event_ids
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_leaves_append_only BEFORE UPDATE OR DELETE ON whitetower.audit_leaves
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_leaves_no_truncate BEFORE TRUNCATE ON whitetower.audit_leaves
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_tree_hashes_append_only BEFORE UPDATE OR DELETE ON whitetower.audit_tree_hashes
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_tree_hashes_no_truncate BEFORE TRUNCATE ON whitetower.audit_tree_hashes
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_checkpoints_append_only BEFORE UPDATE OR DELETE ON whitetower.audit_checkpoints
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER audit_checkpoints_no_truncate BEFORE TRUNCATE ON whitetower.audit_checkpoints
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER lifecycle_transitions_append_only BEFORE UPDATE OR DELETE ON whitetower.lifecycle_transitions
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER lifecycle_transitions_no_truncate BEFORE TRUNCATE ON whitetower.lifecycle_transitions
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER use_case_decisions_append_only BEFORE UPDATE OR DELETE ON whitetower.use_case_decisions
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER use_case_decisions_no_truncate BEFORE TRUNCATE ON whitetower.use_case_decisions
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER policy_approvals_append_only BEFORE UPDATE OR DELETE ON whitetower.policy_approvals
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER policy_approvals_no_truncate BEFORE TRUNCATE ON whitetower.policy_approvals
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER policy_bundles_append_only BEFORE UPDATE OR DELETE ON whitetower.policy_bundles
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER policy_bundles_no_truncate BEFORE TRUNCATE ON whitetower.policy_bundles
  FOR EACH STATEMENT EXECUTE FUNCTION whitetower.reject_change();
CREATE TRIGGER policy_versions_never_deleted BEFORE DELETE ON whitetower.policy_versions
  FOR EACH ROW EXECUTE FUNCTION whitetower.reject_change();

-- Privileges of the runtime role -----------------------------------------------------------
-- Listed table by table on purpose: nothing is granted by default.

GRANT SELECT, INSERT, UPDATE ON
  whitetower.principals, whitetower.role_bindings, whitetower.api_tokens,
  whitetower.use_cases, whitetower.agents, whitetower.agent_owners, whitetower.ownership_transfers,
  whitetower.reviews, whitetower.signing_keys, whitetower.modules, whitetower.machine_credentials,
  whitetower.workload_issuers, whitetower.workload_identity_bindings,
  whitetower.policies, whitetower.policy_versions,
  whitetower.module_agent_bindings, whitetower.module_instances, whitetower.instance_agents,
  whitetower.governance_state, whitetower.halts, whitetower.halt_acks, whitetower.halt_release_requests,
  whitetower.audit_source_sequences, whitetower.audit_export_cursors,
  whitetower.settings, whitetower.job_state, whitetower.inbox_items
  TO whitetower_runtime;

-- Append-only for the runtime role.
GRANT SELECT, INSERT ON
  whitetower.use_case_decisions, whitetower.lifecycle_transitions,
  whitetower.policy_approvals, whitetower.policy_bundles,
  whitetower.audit_events, whitetower.audit_event_ids, whitetower.audit_leaves,
  whitetower.audit_tree_hashes, whitetower.audit_checkpoints
  TO whitetower_runtime;

-- Short-lived operational data that jobs clean up.
GRANT SELECT, INSERT, UPDATE, DELETE ON
  whitetower.sessions, whitetower.used_assertions, whitetower.outbox
  TO whitetower_runtime;

GRANT SELECT, UPDATE ON whitetower.fleet_state TO whitetower_runtime;
GRANT USAGE ON SEQUENCE whitetower.governance_state_version_seq TO whitetower_runtime;
GRANT EXECUTE ON FUNCTION whitetower.ensure_audit_partitions(integer) TO whitetower_runtime;
