// Module contracts v0.1 (RFC-0001): evidence from module instances.
// Normative text: docs/contracts/module-contract-v0.1.md, section 8.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whitetower/module/v1alpha1/events.proto

package modulev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventStatus says what the core did with an event.
type EventStatus int32

const (
	// Unknown. Keep the event and retry.
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	// Stored for the audit log. The instance may drop it from its buffer.
	EventStatus_EVENT_STATUS_ACCEPTED EventStatus = 1
	// Already stored earlier. The instance may drop it from its buffer.
	EventStatus_EVENT_STATUS_DUPLICATE EventStatus = 2
	// Can never be accepted, for example an undeclared type or an invalid
	// schema. The instance must not retry it (contract, section 8.4).
	EventStatus_EVENT_STATUS_REJECTED EventStatus = 3
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "EVENT_STATUS_ACCEPTED",
		2: "EVENT_STATUS_DUPLICATE",
		3: "EVENT_STATUS_REJECTED",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"EVENT_STATUS_ACCEPTED":    1,
		"EVENT_STATUS_DUPLICATE":   2,
		"EVENT_STATUS_REJECTED":    3,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_events_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_events_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_events_proto_rawDescGZIP(), []int{0}
}

// PublishRequest carries a batch of events.
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier returned by RegisterInstance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// At most 500 events, each a CloudEvent 1.0 in JSON structured mode (UTF-8),
	// of at most 64 KiB, in the order they were recorded.
	Events        [][]byte `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PublishRequest) GetEvents() [][]byte {
	if x != nil {
		return x.Events
	}
	return nil
}

// PublishResponse reports what happened to each event.
type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One result per event, in the order of the request.
	Results       []*EventResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetResults() []*EventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// EventResult is the outcome for one event.
type EventResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the core did.
	Status EventStatus `protobuf:"varint,1,opt,name=status,proto3,enum=whitetower.module.v1alpha1.EventStatus" json:"status,omitempty"`
	// For a rejection, why.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResult) Reset() {
	*x = EventResult{}
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResult) ProtoMessage() {}

func (x *EventResult) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResult.ProtoReflect.Descriptor instead.
func (*EventResult) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventResult) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *EventResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_whitetower_module_v1alpha1_events_proto protoreflect.FileDescriptor

const file_whitetower_module_v1alpha1_events_proto_rawDesc = "" +
	"\n" +
	"'whitetower/module/v1alpha1/events.proto\x12\x1awhitetower.module.v1alpha1\"I\n" +
	"\x0ePublishRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06events\x18\x02 \x03(\fR\x06events\"T\n" +
	"\x0fPublishResponse\x12A\n" +
	"\aresults\x18\x01 \x03(\v2'.whitetower.module.v1alpha1.EventResultR\aresults\"f\n" +
	"\vEventResult\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.whitetower.module.v1alpha1.EventStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*}\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16EVENT_STATUS_DUPLICATE\x10\x02\x12\x19\n" +
	"\x15EVENT_STATUS_REJECTED\x10\x032w\n" +
	"\fEventService\x12g\n" +
	"\aPublish\x12*.whitetower.module.v1alpha1.PublishRequest\x1a+.whitetower.module.v1alpha1.PublishResponse\"\x03\x90\x02\x02B\x8c\x02\n" +
	"\x1ecom.whitetower.module.v1alpha1B\vEventsProtoP\x01ZSgithub.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1;modulev1alpha1\xa2\x02\x03WMX\xaa\x02\x1aWhitetower.Module.V1alpha1\xca\x02\x1aWhitetower\\Module\\V1alpha1\xe2\x02&Whitetower\\Module\\V1alpha1\\GPBMetadata\xea\x02\x1cWhitetower::Module::V1alpha1b\x06proto3"

var (
	file_whitetower_module_v1alpha1_events_proto_rawDescOnce sync.Once
	file_whitetower_module_v1alpha1_events_proto_rawDescData []byte
)

func file_whitetower_module_v1alpha1_events_proto_rawDescGZIP() []byte {
	file_whitetower_module_v1alpha1_events_proto_rawDescOnce.Do(func() {
		file_whitetower_module_v1alpha1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_events_proto_rawDesc), len(file_whitetower_module_v1alpha1_events_proto_rawDesc)))
	})
	return file_whitetower_module_v1alpha1_events_proto_rawDescData
}

var file_whitetower_module_v1alpha1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whitetower_module_v1alpha1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_whitetower_module_v1alpha1_events_proto_goTypes = []any{
	(EventStatus)(0),        // 0: whitetower.module.v1alpha1.EventStatus
	(*PublishRequest)(nil),  // 1: whitetower.module.v1alpha1.PublishRequest
	(*PublishResponse)(nil), // 2: whitetower.module.v1alpha1.PublishResponse
	(*EventResult)(nil),     // 3: whitetower.module.v1alpha1.EventResult
}
var file_whitetower_module_v1alpha1_events_proto_depIdxs = []int32{
	3, // 0: whitetower.module.v1alpha1.PublishResponse.results:type_name -> whitetower.module.v1alpha1.EventResult
	0, // 1: whitetower.module.v1alpha1.EventResult.status:type_name -> whitetower.module.v1alpha1.EventStatus
	1, // 2: whitetower.module.v1alpha1.EventService.Publish:input_type -> whitetower.module.v1alpha1.PublishRequest
	2, // 3: whitetower.module.v1alpha1.EventService.Publish:output_type -> whitetower.module.v1alpha1.PublishResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_whitetower_module_v1alpha1_events_proto_init() }
func file_whitetower_module_v1alpha1_events_proto_init() {
	if File_whitetower_module_v1alpha1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_events_proto_rawDesc), len(file_whitetower_module_v1alpha1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitetower_module_v1alpha1_events_proto_goTypes,
		DependencyIndexes: file_whitetower_module_v1alpha1_events_proto_depIdxs,
		EnumInfos:         file_whitetower_module_v1alpha1_events_proto_enumTypes,
		MessageInfos:      file_whitetower_module_v1alpha1_events_proto_msgTypes,
	}.Build()
	File_whitetower_module_v1alpha1_events_proto = out.File
	file_whitetower_module_v1alpha1_events_proto_goTypes = nil
	file_whitetower_module_v1alpha1_events_proto_depIdxs = nil
}
