// Module contracts v0.1 (RFC-0001): governance state, leases and acknowledgements.
// Normative text: docs/contracts/module-contract-v0.1.md, sections 5 and 6.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whitetower/module/v1alpha1/governance.proto

package modulev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LifecycleState is the agent's lifecycle state (docs/architecture/lifecycle.md).
// The gate may open only in the validated, ready and active states; any other
// value, including values unknown to the client, keeps it closed.
type LifecycleState int32

const (
	// Unknown. Keeps the gate closed.
	LifecycleState_LIFECYCLE_STATE_UNSPECIFIED LifecycleState = 0
	// The owner is preparing the proposal.
	LifecycleState_LIFECYCLE_STATE_DRAFT LifecycleState = 1
	// Waiting for the advisory committee.
	LifecycleState_LIFECYCLE_STATE_PROPOSED LifecycleState = 2
	// Use case validated; non-production use only.
	LifecycleState_LIFECYCLE_STATE_VALIDATED LifecycleState = 3
	// Ready to be activated; non-production use only.
	LifecycleState_LIFECYCLE_STATE_READY LifecycleState = 4
	// In production.
	LifecycleState_LIFECYCLE_STATE_ACTIVE LifecycleState = 5
	// Temporarily barred.
	LifecycleState_LIFECYCLE_STATE_SUSPENDED LifecycleState = 6
	// Permanently out of service.
	LifecycleState_LIFECYCLE_STATE_RETIRED LifecycleState = 7
	// The proposal was rejected.
	LifecycleState_LIFECYCLE_STATE_REJECTED LifecycleState = 8
)

// Enum value maps for LifecycleState.
var (
	LifecycleState_name = map[int32]string{
		0: "LIFECYCLE_STATE_UNSPECIFIED",
		1: "LIFECYCLE_STATE_DRAFT",
		2: "LIFECYCLE_STATE_PROPOSED",
		3: "LIFECYCLE_STATE_VALIDATED",
		4: "LIFECYCLE_STATE_READY",
		5: "LIFECYCLE_STATE_ACTIVE",
		6: "LIFECYCLE_STATE_SUSPENDED",
		7: "LIFECYCLE_STATE_RETIRED",
		8: "LIFECYCLE_STATE_REJECTED",
	}
	LifecycleState_value = map[string]int32{
		"LIFECYCLE_STATE_UNSPECIFIED": 0,
		"LIFECYCLE_STATE_DRAFT":       1,
		"LIFECYCLE_STATE_PROPOSED":    2,
		"LIFECYCLE_STATE_VALIDATED":   3,
		"LIFECYCLE_STATE_READY":       4,
		"LIFECYCLE_STATE_ACTIVE":      5,
		"LIFECYCLE_STATE_SUSPENDED":   6,
		"LIFECYCLE_STATE_RETIRED":     7,
		"LIFECYCLE_STATE_REJECTED":    8,
	}
)

func (x LifecycleState) Enum() *LifecycleState {
	p := new(LifecycleState)
	*p = x
	return p
}

func (x LifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[0].Descriptor()
}

func (LifecycleState) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[0]
}

func (x LifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleState.Descriptor instead.
func (LifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{0}
}

// HaltScope says what a halt targets.
type HaltScope int32

const (
	// Unknown. Still a halt.
	HaltScope_HALT_SCOPE_UNSPECIFIED HaltScope = 0
	// One agent.
	HaltScope_HALT_SCOPE_AGENT HaltScope = 1
	// The agents matching a selector.
	HaltScope_HALT_SCOPE_SELECTOR HaltScope = 2
	// Every agent.
	HaltScope_HALT_SCOPE_FLEET HaltScope = 3
)

// Enum value maps for HaltScope.
var (
	HaltScope_name = map[int32]string{
		0: "HALT_SCOPE_UNSPECIFIED",
		1: "HALT_SCOPE_AGENT",
		2: "HALT_SCOPE_SELECTOR",
		3: "HALT_SCOPE_FLEET",
	}
	HaltScope_value = map[string]int32{
		"HALT_SCOPE_UNSPECIFIED": 0,
		"HALT_SCOPE_AGENT":       1,
		"HALT_SCOPE_SELECTOR":    2,
		"HALT_SCOPE_FLEET":       3,
	}
)

func (x HaltScope) Enum() *HaltScope {
	p := new(HaltScope)
	*p = x
	return p
}

func (x HaltScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaltScope) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[1].Descriptor()
}

func (HaltScope) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[1]
}

func (x HaltScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaltScope.Descriptor instead.
func (HaltScope) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{1}
}

// HaltMode says how far an enforcement point goes with work already in flight.
// Every mode closes the gate at once.
type HaltMode int32

const (
	// Unknown. Treated as HALT_MODE_INTERRUPT.
	HaltMode_HALT_MODE_UNSPECIFIED HaltMode = 0
	// Close the gate only; work in flight finishes.
	HaltMode_HALT_MODE_BLOCK HaltMode = 1
	// Close the gate and interrupt work in flight where the framework allows it.
	HaltMode_HALT_MODE_INTERRUPT HaltMode = 2
	// Close the gate, interrupt, then end the agent's process after a grace period.
	HaltMode_HALT_MODE_TERMINATE HaltMode = 3
)

// Enum value maps for HaltMode.
var (
	HaltMode_name = map[int32]string{
		0: "HALT_MODE_UNSPECIFIED",
		1: "HALT_MODE_BLOCK",
		2: "HALT_MODE_INTERRUPT",
		3: "HALT_MODE_TERMINATE",
	}
	HaltMode_value = map[string]int32{
		"HALT_MODE_UNSPECIFIED": 0,
		"HALT_MODE_BLOCK":       1,
		"HALT_MODE_INTERRUPT":   2,
		"HALT_MODE_TERMINATE":   3,
	}
)

func (x HaltMode) Enum() *HaltMode {
	p := new(HaltMode)
	*p = x
	return p
}

func (x HaltMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaltMode) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[2].Descriptor()
}

func (HaltMode) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[2]
}

func (x HaltMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaltMode.Descriptor instead.
func (HaltMode) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{2}
}

// HaltLayer is one layer of a halt (architecture, sections 6.1 and 6.2).
type HaltLayer int32

const (
	// Unknown.
	HaltLayer_HALT_LAYER_UNSPECIFIED HaltLayer = 0
	// Every further governed call and interaction is denied (KIL-01).
	HaltLayer_HALT_LAYER_GATE_CLOSED HaltLayer = 1
	// The work in flight was interrupted.
	HaltLayer_HALT_LAYER_IN_FLIGHT_INTERRUPTED HaltLayer = 2
	// The agent's process ended.
	HaltLayer_HALT_LAYER_PROCESS_TERMINATED HaltLayer = 3
	// The agent's workloads were isolated at the network level (KIL-10).
	HaltLayer_HALT_LAYER_NETWORK_QUARANTINED HaltLayer = 4
)

// Enum value maps for HaltLayer.
var (
	HaltLayer_name = map[int32]string{
		0: "HALT_LAYER_UNSPECIFIED",
		1: "HALT_LAYER_GATE_CLOSED",
		2: "HALT_LAYER_IN_FLIGHT_INTERRUPTED",
		3: "HALT_LAYER_PROCESS_TERMINATED",
		4: "HALT_LAYER_NETWORK_QUARANTINED",
	}
	HaltLayer_value = map[string]int32{
		"HALT_LAYER_UNSPECIFIED":           0,
		"HALT_LAYER_GATE_CLOSED":           1,
		"HALT_LAYER_IN_FLIGHT_INTERRUPTED": 2,
		"HALT_LAYER_PROCESS_TERMINATED":    3,
		"HALT_LAYER_NETWORK_QUARANTINED":   4,
	}
)

func (x HaltLayer) Enum() *HaltLayer {
	p := new(HaltLayer)
	*p = x
	return p
}

func (x HaltLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HaltLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[3].Descriptor()
}

func (HaltLayer) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[3]
}

func (x HaltLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HaltLayer.Descriptor instead.
func (HaltLayer) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{3}
}

// LayerOutcome says what happened at one layer.
type LayerOutcome int32

const (
	// Unknown. Never counts as done.
	LayerOutcome_LAYER_OUTCOME_UNSPECIFIED LayerOutcome = 0
	// The layer is in place.
	LayerOutcome_LAYER_OUTCOME_DONE LayerOutcome = 1
	// Attempted but not achieved, for example blocking work that is still running.
	LayerOutcome_LAYER_OUTCOME_NOT_DONE LayerOutcome = 2
	// Nothing to do: nothing was in flight, the halt mode excludes the layer, or
	// the agent has no workloads here.
	LayerOutcome_LAYER_OUTCOME_NOT_APPLICABLE LayerOutcome = 3
	// The attempt failed with an error.
	LayerOutcome_LAYER_OUTCOME_FAILED LayerOutcome = 4
)

// Enum value maps for LayerOutcome.
var (
	LayerOutcome_name = map[int32]string{
		0: "LAYER_OUTCOME_UNSPECIFIED",
		1: "LAYER_OUTCOME_DONE",
		2: "LAYER_OUTCOME_NOT_DONE",
		3: "LAYER_OUTCOME_NOT_APPLICABLE",
		4: "LAYER_OUTCOME_FAILED",
	}
	LayerOutcome_value = map[string]int32{
		"LAYER_OUTCOME_UNSPECIFIED":    0,
		"LAYER_OUTCOME_DONE":           1,
		"LAYER_OUTCOME_NOT_DONE":       2,
		"LAYER_OUTCOME_NOT_APPLICABLE": 3,
		"LAYER_OUTCOME_FAILED":         4,
	}
)

func (x LayerOutcome) Enum() *LayerOutcome {
	p := new(LayerOutcome)
	*p = x
	return p
}

func (x LayerOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[4].Descriptor()
}

func (LayerOutcome) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[4]
}

func (x LayerOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerOutcome.Descriptor instead.
func (LayerOutcome) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{4}
}

// BundleOutcome says what the instance did with a bundle.
type BundleOutcome int32

const (
	// Unknown.
	BundleOutcome_BUNDLE_OUTCOME_UNSPECIFIED BundleOutcome = 0
	// Verified and active.
	BundleOutcome_BUNDLE_OUTCOME_ACTIVATED BundleOutcome = 1
	// Refused; the previous bundle, if any, stays active.
	BundleOutcome_BUNDLE_OUTCOME_REJECTED BundleOutcome = 2
)

// Enum value maps for BundleOutcome.
var (
	BundleOutcome_name = map[int32]string{
		0: "BUNDLE_OUTCOME_UNSPECIFIED",
		1: "BUNDLE_OUTCOME_ACTIVATED",
		2: "BUNDLE_OUTCOME_REJECTED",
	}
	BundleOutcome_value = map[string]int32{
		"BUNDLE_OUTCOME_UNSPECIFIED": 0,
		"BUNDLE_OUTCOME_ACTIVATED":   1,
		"BUNDLE_OUTCOME_REJECTED":    2,
	}
)

func (x BundleOutcome) Enum() *BundleOutcome {
	p := new(BundleOutcome)
	*p = x
	return p
}

func (x BundleOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BundleOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_governance_proto_enumTypes[5].Descriptor()
}

func (BundleOutcome) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_governance_proto_enumTypes[5]
}

func (x BundleOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BundleOutcome.Descriptor instead.
func (BundleOutcome) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{5}
}

// WatchRequest opens or resumes a watch.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier returned by RegisterInstance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// The last state version the instance applied, or 0 for a snapshot. The
	// server may answer with a snapshot even when this is not 0.
	SinceVersion  uint64 `protobuf:"varint,2,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *WatchRequest) GetSinceVersion() uint64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

// WatchResponse is one message of the stream.
type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state version the client has reached once it applies this message.
	// For snapshot parts, the version of the whole snapshot.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// What the message carries.
	//
	// Types that are valid to be assigned to Message:
	//
	//	*WatchResponse_SnapshotPart
	//	*WatchResponse_Change
	//	*WatchResponse_LeaseRenewal
	Message       isWatchResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WatchResponse) GetMessage() isWatchResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WatchResponse) GetSnapshotPart() *SnapshotPart {
	if x != nil {
		if x, ok := x.Message.(*WatchResponse_SnapshotPart); ok {
			return x.SnapshotPart
		}
	}
	return nil
}

func (x *WatchResponse) GetChange() *StateChange {
	if x != nil {
		if x, ok := x.Message.(*WatchResponse_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *WatchResponse) GetLeaseRenewal() *LeaseRenewal {
	if x != nil {
		if x, ok := x.Message.(*WatchResponse_LeaseRenewal); ok {
			return x.LeaseRenewal
		}
	}
	return nil
}

type isWatchResponse_Message interface {
	isWatchResponse_Message()
}

type WatchResponse_SnapshotPart struct {
	// Part of a snapshot. A snapshot replaces the client's whole state, and
	// takes effect only when its last part arrives.
	SnapshotPart *SnapshotPart `protobuf:"bytes,2,opt,name=snapshot_part,json=snapshotPart,proto3,oneof"`
}

type WatchResponse_Change struct {
	// A change after the snapshot, in version order.
	Change *StateChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type WatchResponse_LeaseRenewal struct {
	// Renews the lease of every agent in scope.
	LeaseRenewal *LeaseRenewal `protobuf:"bytes,4,opt,name=lease_renewal,json=leaseRenewal,proto3,oneof"`
}

func (*WatchResponse_SnapshotPart) isWatchResponse_Message() {}

func (*WatchResponse_Change) isWatchResponse_Message() {}

func (*WatchResponse_LeaseRenewal) isWatchResponse_Message() {}

// SnapshotPart is part of a complete state.
type SnapshotPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True for the first part of a snapshot. The client starts collecting a new
	// snapshot and keeps its current state until the last part arrives.
	First bool `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	// True for the last part. The client then replaces its state atomically.
	Last bool `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	// The fleet state. Present in the first part.
	Fleet *FleetState `protobuf:"bytes,3,opt,name=fleet,proto3" json:"fleet,omitempty"`
	// Agents in the instance's scope.
	Agents        []*AgentState `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotPart) Reset() {
	*x = SnapshotPart{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPart) ProtoMessage() {}

func (x *SnapshotPart) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPart.ProtoReflect.Descriptor instead.
func (*SnapshotPart) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotPart) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *SnapshotPart) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *SnapshotPart) GetFleet() *FleetState {
	if x != nil {
		return x.Fleet
	}
	return nil
}

func (x *SnapshotPart) GetAgents() []*AgentState {
	if x != nil {
		return x.Agents
	}
	return nil
}

// StateChange carries the new state of what changed.
type StateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete new state of each agent that changed, or that entered the
	// instance's scope.
	Agents []*AgentState `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// The new fleet state, when it changed.
	Fleet *FleetState `protobuf:"bytes,2,opt,name=fleet,proto3" json:"fleet,omitempty"`
	// Agents that left the instance's scope. The instance must deny everything
	// for them from now on.
	RemovedAgentIds []string `protobuf:"bytes,3,rep,name=removed_agent_ids,json=removedAgentIds,proto3" json:"removed_agent_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{3}
}

func (x *StateChange) GetAgents() []*AgentState {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *StateChange) GetFleet() *FleetState {
	if x != nil {
		return x.Fleet
	}
	return nil
}

func (x *StateChange) GetRemovedAgentIds() []string {
	if x != nil {
		return x.RemovedAgentIds
	}
	return nil
}

// LeaseRenewal renews the lease of every agent in scope, if it is fresh. Each
// lease then lasts that agent's lease_ttl, measured on the client's monotonic
// clock from the moment it received this message.
type LeaseRenewal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The core's clock when it sent the renewal. Required. A client ignores a
	// renewal without it, or older than its tolerance (5 seconds by default) on
	// the client's own clock, so a stream held back on its way lets leases run
	// out instead of delaying halts (contract, section 5.3).
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRenewal) Reset() {
	*x = LeaseRenewal{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRenewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRenewal) ProtoMessage() {}

func (x *LeaseRenewal) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRenewal.ProtoReflect.Descriptor instead.
func (*LeaseRenewal) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseRenewal) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// AgentState is what the core publishes about one agent.
type AgentState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent's identifier (UUIDv7).
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The state version of this agent's last change.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// The agent's human-readable identifier, for logs.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// Where the agent is in the governance process. It decides whether the gate
	// may open.
	LifecycleState LifecycleState `protobuf:"varint,4,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=whitetower.module.v1alpha1.LifecycleState" json:"lifecycle_state,omitempty"`
	// Agent and selector halts that cover the agent. The agent is halted when
	// this list is not empty or when the fleet is halted.
	Halts []*Halt `protobuf:"bytes,5,rep,name=halts,proto3" json:"halts,omitempty"`
	// The agent's effective policy bundle. Absent while it has none.
	Bundle *BundleRef `protobuf:"bytes,6,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// How long the lease lasts after each renewal.
	LeaseTtl *durationpb.Duration `protobuf:"bytes,7,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	// What the agent's owner chose to happen to work in flight when it is halted.
	HaltMode HaltMode `protobuf:"varint,8,opt,name=halt_mode,json=haltMode,proto3,enum=whitetower.module.v1alpha1.HaltMode" json:"halt_mode,omitempty"`
	// What policies may use about the agent (decision profile).
	Attributes    *AgentAttributes `protobuf:"bytes,9,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{5}
}

func (x *AgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AgentState) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AgentState) GetLifecycleState() LifecycleState {
	if x != nil {
		return x.LifecycleState
	}
	return LifecycleState_LIFECYCLE_STATE_UNSPECIFIED
}

func (x *AgentState) GetHalts() []*Halt {
	if x != nil {
		return x.Halts
	}
	return nil
}

func (x *AgentState) GetBundle() *BundleRef {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *AgentState) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

func (x *AgentState) GetHaltMode() HaltMode {
	if x != nil {
		return x.HaltMode
	}
	return HaltMode_HALT_MODE_UNSPECIFIED
}

func (x *AgentState) GetAttributes() *AgentAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// FleetState is the state that applies to every agent.
type FleetState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state version of the fleet state's last change.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Active fleet halts. Every agent is halted while this list is not empty.
	Halts         []*Halt `protobuf:"bytes,2,rep,name=halts,proto3" json:"halts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetState) Reset() {
	*x = FleetState{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetState) ProtoMessage() {}

func (x *FleetState) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetState.ProtoReflect.Descriptor instead.
func (*FleetState) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{6}
}

func (x *FleetState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FleetState) GetHalts() []*Halt {
	if x != nil {
		return x.Halts
	}
	return nil
}

// Halt identifies an active halt. Reasons are not sent to instances; operators
// see them in the console.
type Halt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The halt's identifier (UUIDv7).
	HaltId string `protobuf:"bytes,1,opt,name=halt_id,json=haltId,proto3" json:"halt_id,omitempty"`
	// What the halt targets.
	Scope HaltScope `protobuf:"varint,2,opt,name=scope,proto3,enum=whitetower.module.v1alpha1.HaltScope" json:"scope,omitempty"`
	// When the halt was issued (server time).
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// True for a kill switch drill (KIL-09), which instances handle as a real halt.
	Drill         bool `protobuf:"varint,4,opt,name=drill,proto3" json:"drill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Halt) Reset() {
	*x = Halt{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halt) ProtoMessage() {}

func (x *Halt) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halt.ProtoReflect.Descriptor instead.
func (*Halt) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{7}
}

func (x *Halt) GetHaltId() string {
	if x != nil {
		return x.HaltId
	}
	return ""
}

func (x *Halt) GetScope() HaltScope {
	if x != nil {
		return x.Scope
	}
	return HaltScope_HALT_SCOPE_UNSPECIFIED
}

func (x *Halt) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Halt) GetDrill() bool {
	if x != nil {
		return x.Drill
	}
	return false
}

// BundleRef identifies the agent's effective policy bundle.
type BundleRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bundle version, monotonic per agent.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Lowercase hexadecimal SHA-256 of the bundle's manifest bytes.
	ManifestSha256 string `protobuf:"bytes,2,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	// Total size of the manifest and the files, in bytes.
	SizeBytes     uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleRef) Reset() {
	*x = BundleRef{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleRef) ProtoMessage() {}

func (x *BundleRef) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleRef.ProtoReflect.Descriptor instead.
func (*BundleRef) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{8}
}

func (x *BundleRef) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BundleRef) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *BundleRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// AgentAttributes are the facts about an agent that policies may use. They map
// to the attributes and tags of the Cedar principal (decision profile).
type AgentAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "in_house" or "third_party".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// "low", "medium", "high" or "critical".
	RiskTier string `protobuf:"bytes,2,opt,name=risk_tier,json=riskTier,proto3" json:"risk_tier,omitempty"`
	// Data categories the agent accesses, from the organization's taxonomy.
	DataCategories []string `protobuf:"bytes,3,rep,name=data_categories,json=dataCategories,proto3" json:"data_categories,omitempty"`
	// Free-form labels set in the inventory.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Pseudonymous principal ID of the agent's primary owner. Never a name or an
	// email address.
	OwnerId       string `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAttributes) Reset() {
	*x = AgentAttributes{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAttributes) ProtoMessage() {}

func (x *AgentAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAttributes.ProtoReflect.Descriptor instead.
func (*AgentAttributes) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{9}
}

func (x *AgentAttributes) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentAttributes) GetRiskTier() string {
	if x != nil {
		return x.RiskTier
	}
	return ""
}

func (x *AgentAttributes) GetDataCategories() []string {
	if x != nil {
		return x.DataCategories
	}
	return nil
}

func (x *AgentAttributes) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentAttributes) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// AcknowledgeRequest carries one or more acknowledgements.
type AcknowledgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier returned by RegisterInstance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// At most 100 acknowledgements.
	Acknowledgements []*Acknowledgement `protobuf:"bytes,2,rep,name=acknowledgements,proto3" json:"acknowledgements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{10}
}

func (x *AcknowledgeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AcknowledgeRequest) GetAcknowledgements() []*Acknowledgement {
	if x != nil {
		return x.Acknowledgements
	}
	return nil
}

// Acknowledgement reports one thing the instance did.
type Acknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier chosen by the instance (UUID). A retry reuses it, so the core
	// records each acknowledgement once.
	AcknowledgementId string `protobuf:"bytes,1,opt,name=acknowledgement_id,json=acknowledgementId,proto3" json:"acknowledgement_id,omitempty"`
	// The agent it concerns.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// What is acknowledged.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Acknowledgement_Halt
	//	*Acknowledgement_Bundle
	//	*Acknowledgement_State
	Kind          isAcknowledgement_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{11}
}

func (x *Acknowledgement) GetAcknowledgementId() string {
	if x != nil {
		return x.AcknowledgementId
	}
	return ""
}

func (x *Acknowledgement) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Acknowledgement) GetKind() isAcknowledgement_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Acknowledgement) GetHalt() *HaltAcknowledgement {
	if x != nil {
		if x, ok := x.Kind.(*Acknowledgement_Halt); ok {
			return x.Halt
		}
	}
	return nil
}

func (x *Acknowledgement) GetBundle() *BundleAcknowledgement {
	if x != nil {
		if x, ok := x.Kind.(*Acknowledgement_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

func (x *Acknowledgement) GetState() *StateAcknowledgement {
	if x != nil {
		if x, ok := x.Kind.(*Acknowledgement_State); ok {
			return x.State
		}
	}
	return nil
}

type isAcknowledgement_Kind interface {
	isAcknowledgement_Kind()
}

type Acknowledgement_Halt struct {
	// What a halt achieved, layer by layer.
	Halt *HaltAcknowledgement `protobuf:"bytes,3,opt,name=halt,proto3,oneof"`
}

type Acknowledgement_Bundle struct {
	// A bundle activated or rejected.
	Bundle *BundleAcknowledgement `protobuf:"bytes,4,opt,name=bundle,proto3,oneof"`
}

type Acknowledgement_State struct {
	// The state version applied.
	State *StateAcknowledgement `protobuf:"bytes,5,opt,name=state,proto3,oneof"`
}

func (*Acknowledgement_Halt) isAcknowledgement_Kind() {}

func (*Acknowledgement_Bundle) isAcknowledgement_Kind() {}

func (*Acknowledgement_State) isAcknowledgement_Kind() {}

// HaltAcknowledgement reports halt layers. An instance may acknowledge a halt
// several times as layers complete, for example the gate at once and the
// interruption after its grace period.
type HaltAcknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The halt, including a fleet halt.
	HaltId string `protobuf:"bytes,1,opt,name=halt_id,json=haltId,proto3" json:"halt_id,omitempty"`
	// One report per layer the instance handles.
	Layers        []*HaltLayerReport `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaltAcknowledgement) Reset() {
	*x = HaltAcknowledgement{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaltAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaltAcknowledgement) ProtoMessage() {}

func (x *HaltAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaltAcknowledgement.ProtoReflect.Descriptor instead.
func (*HaltAcknowledgement) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{12}
}

func (x *HaltAcknowledgement) GetHaltId() string {
	if x != nil {
		return x.HaltId
	}
	return ""
}

func (x *HaltAcknowledgement) GetLayers() []*HaltLayerReport {
	if x != nil {
		return x.Layers
	}
	return nil
}

// HaltLayerReport is the outcome of one layer.
type HaltLayerReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The layer.
	Layer HaltLayer `protobuf:"varint,1,opt,name=layer,proto3,enum=whitetower.module.v1alpha1.HaltLayer" json:"layer,omitempty"`
	// What happened.
	Outcome LayerOutcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=whitetower.module.v1alpha1.LayerOutcome" json:"outcome,omitempty"`
	// Time from receiving the halt to this outcome, measured on the instance's
	// monotonic clock.
	AfterReceipt *durationpb.Duration `protobuf:"bytes,3,opt,name=after_receipt,json=afterReceipt,proto3" json:"after_receipt,omitempty"`
	// The instance's wall-clock time of the outcome. Informational.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// Short explanation, for example "blocking tool still running".
	Detail string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	// For HALT_LAYER_NETWORK_QUARANTINED: the number of workloads isolated.
	Workloads     uint32 `protobuf:"varint,6,opt,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HaltLayerReport) Reset() {
	*x = HaltLayerReport{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HaltLayerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HaltLayerReport) ProtoMessage() {}

func (x *HaltLayerReport) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HaltLayerReport.ProtoReflect.Descriptor instead.
func (*HaltLayerReport) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{13}
}

func (x *HaltLayerReport) GetLayer() HaltLayer {
	if x != nil {
		return x.Layer
	}
	return HaltLayer_HALT_LAYER_UNSPECIFIED
}

func (x *HaltLayerReport) GetOutcome() LayerOutcome {
	if x != nil {
		return x.Outcome
	}
	return LayerOutcome_LAYER_OUTCOME_UNSPECIFIED
}

func (x *HaltLayerReport) GetAfterReceipt() *durationpb.Duration {
	if x != nil {
		return x.AfterReceipt
	}
	return nil
}

func (x *HaltLayerReport) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *HaltLayerReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HaltLayerReport) GetWorkloads() uint32 {
	if x != nil {
		return x.Workloads
	}
	return 0
}

// BundleAcknowledgement reports a bundle activation or rejection.
type BundleAcknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bundle version.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Lowercase hexadecimal SHA-256 of the manifest bytes the instance received.
	ManifestSha256 string `protobuf:"bytes,2,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	// What the instance did.
	Outcome BundleOutcome `protobuf:"varint,3,opt,name=outcome,proto3,enum=whitetower.module.v1alpha1.BundleOutcome" json:"outcome,omitempty"`
	// For a rejection, a reason code of the contract (section 7.5).
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleAcknowledgement) Reset() {
	*x = BundleAcknowledgement{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleAcknowledgement) ProtoMessage() {}

func (x *BundleAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleAcknowledgement.ProtoReflect.Descriptor instead.
func (*BundleAcknowledgement) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{14}
}

func (x *BundleAcknowledgement) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BundleAcknowledgement) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *BundleAcknowledgement) GetOutcome() BundleOutcome {
	if x != nil {
		return x.Outcome
	}
	return BundleOutcome_BUNDLE_OUTCOME_UNSPECIFIED
}

func (x *BundleAcknowledgement) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StateAcknowledgement reports the state version applied, so the console can
// show instances that lag behind.
type StateAcknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last state version applied.
	Version       uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAcknowledgement) Reset() {
	*x = StateAcknowledgement{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAcknowledgement) ProtoMessage() {}

func (x *StateAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAcknowledgement.ProtoReflect.Descriptor instead.
func (*StateAcknowledgement) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{15}
}

func (x *StateAcknowledgement) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// AcknowledgeResponse is empty: the acknowledgements were recorded.
type AcknowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeResponse) Reset() {
	*x = AcknowledgeResponse{}
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResponse) ProtoMessage() {}

func (x *AcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_governance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP(), []int{16}
}

var File_whitetower_module_v1alpha1_governance_proto protoreflect.FileDescriptor

const file_whitetower_module_v1alpha1_governance_proto_rawDesc = "" +
	"\n" +
	"+whitetower/module/v1alpha1/governance.proto\x12\x1awhitetower.module.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rsince_version\x18\x02 \x01(\x04R\fsinceVersion\"\x99\x02\n" +
	"\rWatchResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12O\n" +
	"\rsnapshot_part\x18\x02 \x01(\v2(.whitetower.module.v1alpha1.SnapshotPartH\x00R\fsnapshotPart\x12A\n" +
	"\x06change\x18\x03 \x01(\v2'.whitetower.module.v1alpha1.StateChangeH\x00R\x06change\x12O\n" +
	"\rlease_renewal\x18\x04 \x01(\v2(.whitetower.module.v1alpha1.LeaseRenewalH\x00R\fleaseRenewalB\t\n" +
	"\amessage\"\xb6\x01\n" +
	"\fSnapshotPart\x12\x14\n" +
	"\x05first\x18\x01 \x01(\bR\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last\x12<\n" +
	"\x05fleet\x18\x03 \x01(\v2&.whitetower.module.v1alpha1.FleetStateR\x05fleet\x12>\n" +
	"\x06agents\x18\x04 \x03(\v2&.whitetower.module.v1alpha1.AgentStateR\x06agents\"\xb7\x01\n" +
	"\vStateChange\x12>\n" +
	"\x06agents\x18\x01 \x03(\v2&.whitetower.module.v1alpha1.AgentStateR\x06agents\x12<\n" +
	"\x05fleet\x18\x02 \x01(\v2&.whitetower.module.v1alpha1.FleetStateR\x05fleet\x12*\n" +
	"\x11removed_agent_ids\x18\x03 \x03(\tR\x0fremovedAgentIds\"K\n" +
	"\fLeaseRenewal\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xe9\x03\n" +
	"\n" +
	"AgentState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12S\n" +
	"\x0flifecycle_state\x18\x04 \x01(\x0e2*.whitetower.module.v1alpha1.LifecycleStateR\x0elifecycleState\x126\n" +
	"\x05halts\x18\x05 \x03(\v2 .whitetower.module.v1alpha1.HaltR\x05halts\x12=\n" +
	"\x06bundle\x18\x06 \x01(\v2%.whitetower.module.v1alpha1.BundleRefR\x06bundle\x126\n" +
	"\tlease_ttl\x18\a \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\x12A\n" +
	"\thalt_mode\x18\b \x01(\x0e2$.whitetower.module.v1alpha1.HaltModeR\bhaltMode\x12K\n" +
	"\n" +
	"attributes\x18\t \x01(\v2+.whitetower.module.v1alpha1.AgentAttributesR\n" +
	"attributes\"^\n" +
	"\n" +
	"FleetState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x126\n" +
	"\x05halts\x18\x02 \x03(\v2 .whitetower.module.v1alpha1.HaltR\x05halts\"\xab\x01\n" +
	"\x04Halt\x12\x17\n" +
	"\ahalt_id\x18\x01 \x01(\tR\x06haltId\x12;\n" +
	"\x05scope\x18\x02 \x01(\x0e2%.whitetower.module.v1alpha1.HaltScopeR\x05scope\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x14\n" +
	"\x05drill\x18\x04 \x01(\bR\x05drill\"m\n" +
	"\tBundleRef\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12'\n" +
	"\x0fmanifest_sha256\x18\x02 \x01(\tR\x0emanifestSha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"\x92\x02\n" +
	"\x0fAgentAttributes\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\trisk_tier\x18\x02 \x01(\tR\briskTier\x12'\n" +
	"\x0fdata_categories\x18\x03 \x03(\tR\x0edataCategories\x12O\n" +
	"\x06labels\x18\x04 \x03(\v27.whitetower.module.v1alpha1.AgentAttributes.LabelsEntryR\x06labels\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x12AcknowledgeRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12W\n" +
	"\x10acknowledgements\x18\x02 \x03(\v2+.whitetower.module.v1alpha1.AcknowledgementR\x10acknowledgements\"\xc1\x02\n" +
	"\x0fAcknowledgement\x12-\n" +
	"\x12acknowledgement_id\x18\x01 \x01(\tR\x11acknowledgementId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12E\n" +
	"\x04halt\x18\x03 \x01(\v2/.whitetower.module.v1alpha1.HaltAcknowledgementH\x00R\x04halt\x12K\n" +
	"\x06bundle\x18\x04 \x01(\v21.whitetower.module.v1alpha1.BundleAcknowledgementH\x00R\x06bundle\x12H\n" +
	"\x05state\x18\x05 \x01(\v20.whitetower.module.v1alpha1.StateAcknowledgementH\x00R\x05stateB\x06\n" +
	"\x04kind\"s\n" +
	"\x13HaltAcknowledgement\x12\x17\n" +
	"\ahalt_id\x18\x01 \x01(\tR\x06haltId\x12C\n" +
	"\x06layers\x18\x02 \x03(\v2+.whitetower.module.v1alpha1.HaltLayerReportR\x06layers\"\xc5\x02\n" +
	"\x0fHaltLayerReport\x12;\n" +
	"\x05layer\x18\x01 \x01(\x0e2%.whitetower.module.v1alpha1.HaltLayerR\x05layer\x12B\n" +
	"\aoutcome\x18\x02 \x01(\x0e2(.whitetower.module.v1alpha1.LayerOutcomeR\aoutcome\x12>\n" +
	"\rafter_receipt\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fafterReceipt\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x1c\n" +
	"\tworkloads\x18\x06 \x01(\rR\tworkloads\"\xb7\x01\n" +
	"\x15BundleAcknowledgement\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12'\n" +
	"\x0fmanifest_sha256\x18\x02 \x01(\tR\x0emanifestSha256\x12C\n" +
	"\aoutcome\x18\x03 \x01(\x0e2).whitetower.module.v1alpha1.BundleOutcomeR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"0\n" +
	"\x14StateAcknowledgement\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x15\n" +
	"\x13AcknowledgeResponse*\x9a\x02\n" +
	"\x0eLifecycleState\x12\x1f\n" +
	"\x1bLIFECYCLE_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LIFECYCLE_STATE_DRAFT\x10\x01\x12\x1c\n" +
	"\x18LIFECYCLE_STATE_PROPOSED\x10\x02\x12\x1d\n" +
	"\x19LIFECYCLE_STATE_VALIDATED\x10\x03\x12\x19\n" +
	"\x15LIFECYCLE_STATE_READY\x10\x04\x12\x1a\n" +
	"\x16LIFECYCLE_STATE_ACTIVE\x10\x05\x12\x1d\n" +
	"\x19LIFECYCLE_STATE_SUSPENDED\x10\x06\x12\x1b\n" +
	"\x17LIFECYCLE_STATE_RETIRED\x10\a\x12\x1c\n" +
	"\x18LIFECYCLE_STATE_REJECTED\x10\b*l\n" +
	"\tHaltScope\x12\x1a\n" +
	"\x16HALT_SCOPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HALT_SCOPE_AGENT\x10\x01\x12\x17\n" +
	"\x13HALT_SCOPE_SELECTOR\x10\x02\x12\x14\n" +
	"\x10HALT_SCOPE_FLEET\x10\x03*l\n" +
	"\bHaltMode\x12\x19\n" +
	"\x15HALT_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHALT_MODE_BLOCK\x10\x01\x12\x17\n" +
	"\x13HALT_MODE_INTERRUPT\x10\x02\x12\x17\n" +
	"\x13HALT_MODE_TERMINATE\x10\x03*\xb0\x01\n" +
	"\tHaltLayer\x12\x1a\n" +
	"\x16HALT_LAYER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HALT_LAYER_GATE_CLOSED\x10\x01\x12$\n" +
	" HALT_LAYER_IN_FLIGHT_INTERRUPTED\x10\x02\x12!\n" +
	"\x1dHALT_LAYER_PROCESS_TERMINATED\x10\x03\x12\"\n" +
	"\x1eHALT_LAYER_NETWORK_QUARANTINED\x10\x04*\x9d\x01\n" +
	"\fLayerOutcome\x12\x1d\n" +
	"\x19LAYER_OUTCOME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LAYER_OUTCOME_DONE\x10\x01\x12\x1a\n" +
	"\x16LAYER_OUTCOME_NOT_DONE\x10\x02\x12 \n" +
	"\x1cLAYER_OUTCOME_NOT_APPLICABLE\x10\x03\x12\x18\n" +
	"\x14LAYER_OUTCOME_FAILED\x10\x04*j\n" +
	"\rBundleOutcome\x12\x1e\n" +
	"\x1aBUNDLE_OUTCOME_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BUNDLE_OUTCOME_ACTIVATED\x10\x01\x12\x1b\n" +
	"\x17BUNDLE_OUTCOME_REJECTED\x10\x022\xe8\x01\n" +
	"\x11GovernanceService\x12^\n" +
	"\x05Watch\x12(.whitetower.module.v1alpha1.WatchRequest\x1a).whitetower.module.v1alpha1.WatchResponse0\x01\x12s\n" +
	"\vAcknowledge\x12..whitetower.module.v1alpha1.AcknowledgeRequest\x1a/.whitetower.module.v1alpha1.AcknowledgeResponse\"\x03\x90\x02\x02B\x90\x02\n" +
	"\x1ecom.whitetower.module.v1alpha1B\x0fGovernanceProtoP\x01ZSgithub.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1;modulev1alpha1\xa2\x02\x03WMX\xaa\x02\x1aWhitetower.Module.V1alpha1\xca\x02\x1aWhitetower\\Module\\V1alpha1\xe2\x02&Whitetower\\Module\\V1alpha1\\GPBMetadata\xea\x02\x1cWhitetower::Module::V1alpha1b\x06proto3"

var (
	file_whitetower_module_v1alpha1_governance_proto_rawDescOnce sync.Once
	file_whitetower_module_v1alpha1_governance_proto_rawDescData []byte
)

func file_whitetower_module_v1alpha1_governance_proto_rawDescGZIP() []byte {
	file_whitetower_module_v1alpha1_governance_proto_rawDescOnce.Do(func() {
		file_whitetower_module_v1alpha1_governance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_governance_proto_rawDesc), len(file_whitetower_module_v1alpha1_governance_proto_rawDesc)))
	})
	return file_whitetower_module_v1alpha1_governance_proto_rawDescData
}

var file_whitetower_module_v1alpha1_governance_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_whitetower_module_v1alpha1_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_whitetower_module_v1alpha1_governance_proto_goTypes = []any{
	(LifecycleState)(0),           // 0: whitetower.module.v1alpha1.LifecycleState
	(HaltScope)(0),                // 1: whitetower.module.v1alpha1.HaltScope
	(HaltMode)(0),                 // 2: whitetower.module.v1alpha1.HaltMode
	(HaltLayer)(0),                // 3: whitetower.module.v1alpha1.HaltLayer
	(LayerOutcome)(0),             // 4: whitetower.module.v1alpha1.LayerOutcome
	(BundleOutcome)(0),            // 5: whitetower.module.v1alpha1.BundleOutcome
	(*WatchRequest)(nil),          // 6: whitetower.module.v1alpha1.WatchRequest
	(*WatchResponse)(nil),         // 7: whitetower.module.v1alpha1.WatchResponse
	(*SnapshotPart)(nil),          // 8: whitetower.module.v1alpha1.SnapshotPart
	(*StateChange)(nil),           // 9: whitetower.module.v1alpha1.StateChange
	(*LeaseRenewal)(nil),          // 10: whitetower.module.v1alpha1.LeaseRenewal
	(*AgentState)(nil),            // 11: whitetower.module.v1alpha1.AgentState
	(*FleetState)(nil),            // 12: whitetower.module.v1alpha1.FleetState
	(*Halt)(nil),                  // 13: whitetower.module.v1alpha1.Halt
	(*BundleRef)(nil),             // 14: whitetower.module.v1alpha1.BundleRef
	(*AgentAttributes)(nil),       // 15: whitetower.module.v1alpha1.AgentAttributes
	(*AcknowledgeRequest)(nil),    // 16: whitetower.module.v1alpha1.AcknowledgeRequest
	(*Acknowledgement)(nil),       // 17: whitetower.module.v1alpha1.Acknowledgement
	(*HaltAcknowledgement)(nil),   // 18: whitetower.module.v1alpha1.HaltAcknowledgement
	(*HaltLayerReport)(nil),       // 19: whitetower.module.v1alpha1.HaltLayerReport
	(*BundleAcknowledgement)(nil), // 20: whitetower.module.v1alpha1.BundleAcknowledgement
	(*StateAcknowledgement)(nil),  // 21: whitetower.module.v1alpha1.StateAcknowledgement
	(*AcknowledgeResponse)(nil),   // 22: whitetower.module.v1alpha1.AcknowledgeResponse
	nil,                           // 23: whitetower.module.v1alpha1.AgentAttributes.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 25: google.protobuf.Duration
}
var file_whitetower_module_v1alpha1_governance_proto_depIdxs = []int32{
	8,  // 0: whitetower.module.v1alpha1.WatchResponse.snapshot_part:type_name -> whitetower.module.v1alpha1.SnapshotPart
	9,  // 1: whitetower.module.v1alpha1.WatchResponse.change:type_name -> whitetower.module.v1alpha1.StateChange
	10, // 2: whitetower.module.v1alpha1.WatchResponse.lease_renewal:type_name -> whitetower.module.v1alpha1.LeaseRenewal
	12, // 3: whitetower.module.v1alpha1.SnapshotPart.fleet:type_name -> whitetower.module.v1alpha1.FleetState
	11, // 4: whitetower.module.v1alpha1.SnapshotPart.agents:type_name -> whitetower.module.v1alpha1.AgentState
	11, // 5: whitetower.module.v1alpha1.StateChange.agents:type_name -> whitetower.module.v1alpha1.AgentState
	12, // 6: whitetower.module.v1alpha1.StateChange.fleet:type_name -> whitetower.module.v1alpha1.FleetState
	24, // 7: whitetower.module.v1alpha1.LeaseRenewal.server_time:type_name -> google.protobuf.Timestamp
	0,  // 8: whitetower.module.v1alpha1.AgentState.lifecycle_state:type_name -> whitetower.module.v1alpha1.LifecycleState
	13, // 9: whitetower.module.v1alpha1.AgentState.halts:type_name -> whitetower.module.v1alpha1.Halt
	14, // 10: whitetower.module.v1alpha1.AgentState.bundle:type_name -> whitetower.module.v1alpha1.BundleRef
	25, // 11: whitetower.module.v1alpha1.AgentState.lease_ttl:type_name -> google.protobuf.Duration
	2,  // 12: whitetower.module.v1alpha1.AgentState.halt_mode:type_name -> whitetower.module.v1alpha1.HaltMode
	15, // 13: whitetower.module.v1alpha1.AgentState.attributes:type_name -> whitetower.module.v1alpha1.AgentAttributes
	13, // 14: whitetower.module.v1alpha1.FleetState.halts:type_name -> whitetower.module.v1alpha1.Halt
	1,  // 15: whitetower.module.v1alpha1.Halt.scope:type_name -> whitetower.module.v1alpha1.HaltScope
	24, // 16: whitetower.module.v1alpha1.Halt.issued_at:type_name -> google.protobuf.Timestamp
	23, // 17: whitetower.module.v1alpha1.AgentAttributes.labels:type_name -> whitetower.module.v1alpha1.AgentAttributes.LabelsEntry
	17, // 18: whitetower.module.v1alpha1.AcknowledgeRequest.acknowledgements:type_name -> whitetower.module.v1alpha1.Acknowledgement
	18, // 19: whitetower.module.v1alpha1.Acknowledgement.halt:type_name -> whitetower.module.v1alpha1.HaltAcknowledgement
	20, // 20: whitetower.module.v1alpha1.Acknowledgement.bundle:type_name -> whitetower.module.v1alpha1.BundleAcknowledgement
	21, // 21: whitetower.module.v1alpha1.Acknowledgement.state:type_name -> whitetower.module.v1alpha1.StateAcknowledgement
	19, // 22: whitetower.module.v1alpha1.HaltAcknowledgement.layers:type_name -> whitetower.module.v1alpha1.HaltLayerReport
	3,  // 23: whitetower.module.v1alpha1.HaltLayerReport.layer:type_name -> whitetower.module.v1alpha1.HaltLayer
	4,  // 24: whitetower.module.v1alpha1.HaltLayerReport.outcome:type_name -> whitetower.module.v1alpha1.LayerOutcome
	25, // 25: whitetower.module.v1alpha1.HaltLayerReport.after_receipt:type_name -> google.protobuf.Duration
	24, // 26: whitetower.module.v1alpha1.HaltLayerReport.observed_at:type_name -> google.protobuf.Timestamp
	5,  // 27: whitetower.module.v1alpha1.BundleAcknowledgement.outcome:type_name -> whitetower.module.v1alpha1.BundleOutcome
	6,  // 28: whitetower.module.v1alpha1.GovernanceService.Watch:input_type -> whitetower.module.v1alpha1.WatchRequest
	16, // 29: whitetower.module.v1alpha1.GovernanceService.Acknowledge:input_type -> whitetower.module.v1alpha1.AcknowledgeRequest
	7,  // 30: whitetower.module.v1alpha1.GovernanceService.Watch:output_type -> whitetower.module.v1alpha1.WatchResponse
	22, // 31: whitetower.module.v1alpha1.GovernanceService.Acknowledge:output_type -> whitetower.module.v1alpha1.AcknowledgeResponse
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_whitetower_module_v1alpha1_governance_proto_init() }
func file_whitetower_module_v1alpha1_governance_proto_init() {
	if File_whitetower_module_v1alpha1_governance_proto != nil {
		return
	}
	file_whitetower_module_v1alpha1_governance_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchResponse_SnapshotPart)(nil),
		(*WatchResponse_Change)(nil),
		(*WatchResponse_LeaseRenewal)(nil),
	}
	file_whitetower_module_v1alpha1_governance_proto_msgTypes[11].OneofWrappers = []any{
		(*Acknowledgement_Halt)(nil),
		(*Acknowledgement_Bundle)(nil),
		(*Acknowledgement_State)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_governance_proto_rawDesc), len(file_whitetower_module_v1alpha1_governance_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitetower_module_v1alpha1_governance_proto_goTypes,
		DependencyIndexes: file_whitetower_module_v1alpha1_governance_proto_depIdxs,
		EnumInfos:         file_whitetower_module_v1alpha1_governance_proto_enumTypes,
		MessageInfos:      file_whitetower_module_v1alpha1_governance_proto_msgTypes,
	}.Build()
	File_whitetower_module_v1alpha1_governance_proto = out.File
	file_whitetower_module_v1alpha1_governance_proto_goTypes = nil
	file_whitetower_module_v1alpha1_governance_proto_depIdxs = nil
}
