// Placeholder that exercises the code generation pipeline (plan P0-01).
// The module contracts are defined by RFC-0001 (plan P0-03), which replaces this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whitetower/module/v1alpha1/meta.proto

package modulev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetServerInfoRequest is empty.
type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_whitetower_module_v1alpha1_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_meta_proto_rawDescGZIP(), []int{0}
}

// GetServerInfoResponse describes the server.
type GetServerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Release version of the server, or "dev" for local builds.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Module contract versions the server supports, for example "v1alpha1".
	ContractVersions []string `protobuf:"bytes,2,rep,name=contract_versions,json=contractVersions,proto3" json:"contract_versions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_whitetower_module_v1alpha1_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_meta_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerInfoResponse) GetContractVersions() []string {
	if x != nil {
		return x.ContractVersions
	}
	return nil
}

var File_whitetower_module_v1alpha1_meta_proto protoreflect.FileDescriptor

const file_whitetower_module_v1alpha1_meta_proto_rawDesc = "" +
	"\n" +
	"%whitetower/module/v1alpha1/meta.proto\x12\x1awhitetower.module.v1alpha1\"\x16\n" +
	"\x14GetServerInfoRequest\"^\n" +
	"\x15GetServerInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x11contract_versions\x18\x02 \x03(\tR\x10contractVersions2\x88\x01\n" +
	"\vMetaService\x12y\n" +
	"\rGetServerInfo\x120.whitetower.module.v1alpha1.GetServerInfoRequest\x1a1.whitetower.module.v1alpha1.GetServerInfoResponse\"\x03\x90\x02\x01B\x8a\x02\n" +
	"\x1ecom.whitetower.module.v1alpha1B\tMetaProtoP\x01ZSgithub.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1;modulev1alpha1\xa2\x02\x03WMX\xaa\x02\x1aWhitetower.Module.V1alpha1\xca\x02\x1aWhitetower\\Module\\V1alpha1\xe2\x02&Whitetower\\Module\\V1alpha1\\GPBMetadata\xea\x02\x1cWhitetower::Module::V1alpha1b\x06proto3"

var (
	file_whitetower_module_v1alpha1_meta_proto_rawDescOnce sync.Once
	file_whitetower_module_v1alpha1_meta_proto_rawDescData []byte
)

func file_whitetower_module_v1alpha1_meta_proto_rawDescGZIP() []byte {
	file_whitetower_module_v1alpha1_meta_proto_rawDescOnce.Do(func() {
		file_whitetower_module_v1alpha1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_meta_proto_rawDesc), len(file_whitetower_module_v1alpha1_meta_proto_rawDesc)))
	})
	return file_whitetower_module_v1alpha1_meta_proto_rawDescData
}

var file_whitetower_module_v1alpha1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_whitetower_module_v1alpha1_meta_proto_goTypes = []any{
	(*GetServerInfoRequest)(nil),  // 0: whitetower.module.v1alpha1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil), // 1: whitetower.module.v1alpha1.GetServerInfoResponse
}
var file_whitetower_module_v1alpha1_meta_proto_depIdxs = []int32{
	0, // 0: whitetower.module.v1alpha1.MetaService.GetServerInfo:input_type -> whitetower.module.v1alpha1.GetServerInfoRequest
	1, // 1: whitetower.module.v1alpha1.MetaService.GetServerInfo:output_type -> whitetower.module.v1alpha1.GetServerInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_whitetower_module_v1alpha1_meta_proto_init() }
func file_whitetower_module_v1alpha1_meta_proto_init() {
	if File_whitetower_module_v1alpha1_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_meta_proto_rawDesc), len(file_whitetower_module_v1alpha1_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitetower_module_v1alpha1_meta_proto_goTypes,
		DependencyIndexes: file_whitetower_module_v1alpha1_meta_proto_depIdxs,
		MessageInfos:      file_whitetower_module_v1alpha1_meta_proto_msgTypes,
	}.Build()
	File_whitetower_module_v1alpha1_meta_proto = out.File
	file_whitetower_module_v1alpha1_meta_proto_goTypes = nil
	file_whitetower_module_v1alpha1_meta_proto_depIdxs = nil
}
