// Module contracts v0.1 (RFC-0001): signed policy bundles.
// Normative text: docs/contracts/module-contract-v0.1.md, section 7.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whitetower/module/v1alpha1/policy.proto

package modulev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BundleKeyStatus is the status of a bundle signing key.
type BundleKeyStatus int32

const (
	// Unknown. Not trusted.
	BundleKeyStatus_BUNDLE_KEY_STATUS_UNSPECIFIED BundleKeyStatus = 0
	// Signs new bundles.
	BundleKeyStatus_BUNDLE_KEY_STATUS_ACTIVE BundleKeyStatus = 1
	// Will sign bundles after the next rotation; trust it in advance.
	BundleKeyStatus_BUNDLE_KEY_STATUS_NEXT BundleKeyStatus = 2
	// Signed bundles before the last rotation; still valid for them.
	BundleKeyStatus_BUNDLE_KEY_STATUS_RETIRED BundleKeyStatus = 3
)

// Enum value maps for BundleKeyStatus.
var (
	BundleKeyStatus_name = map[int32]string{
		0: "BUNDLE_KEY_STATUS_UNSPECIFIED",
		1: "BUNDLE_KEY_STATUS_ACTIVE",
		2: "BUNDLE_KEY_STATUS_NEXT",
		3: "BUNDLE_KEY_STATUS_RETIRED",
	}
	BundleKeyStatus_value = map[string]int32{
		"BUNDLE_KEY_STATUS_UNSPECIFIED": 0,
		"BUNDLE_KEY_STATUS_ACTIVE":      1,
		"BUNDLE_KEY_STATUS_NEXT":        2,
		"BUNDLE_KEY_STATUS_RETIRED":     3,
	}
)

func (x BundleKeyStatus) Enum() *BundleKeyStatus {
	p := new(BundleKeyStatus)
	*p = x
	return p
}

func (x BundleKeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BundleKeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_policy_proto_enumTypes[0].Descriptor()
}

func (BundleKeyStatus) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_policy_proto_enumTypes[0]
}

func (x BundleKeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BundleKeyStatus.Descriptor instead.
func (BundleKeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{0}
}

// GetBundleRequest names a bundle.
type GetBundleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The bundle version, from the agent's BundleRef.
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleRequest) Reset() {
	*x = GetBundleRequest{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleRequest) ProtoMessage() {}

func (x *GetBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleRequest.ProtoReflect.Descriptor instead.
func (*GetBundleRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *GetBundleRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetBundleRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetBundleResponse carries the bundle.
type GetBundleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bundle.
	Bundle        *Bundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleResponse) Reset() {
	*x = GetBundleResponse{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleResponse) ProtoMessage() {}

func (x *GetBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleResponse.ProtoReflect.Descriptor instead.
func (*GetBundleResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GetBundleResponse) GetBundle() *Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

// Bundle is a signed, versioned effective policy set.
type Bundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The manifest, exactly as signed: the RFC 8785 canonical JSON of the bundle
	// manifest. Verify the signature over these bytes before parsing them, and
	// never re-serialize them.
	Manifest []byte `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// JWS compact serialization with a detached payload (RFC 7515, appendix F)
	// over the manifest bytes.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The files the manifest lists, and nothing else.
	Files         []*BundleFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Bundle) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *Bundle) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Bundle) GetFiles() []*BundleFile {
	if x != nil {
		return x.Files
	}
	return nil
}

// BundleFile is one file of a bundle.
type BundleFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path, as listed in the manifest.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The file's content.
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleFile) Reset() {
	*x = BundleFile{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleFile) ProtoMessage() {}

func (x *BundleFile) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleFile.ProtoReflect.Descriptor instead.
func (*BundleFile) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *BundleFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BundleFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// GetBundleKeysRequest is empty.
type GetBundleKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleKeysRequest) Reset() {
	*x = GetBundleKeysRequest{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleKeysRequest) ProtoMessage() {}

func (x *GetBundleKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleKeysRequest.ProtoReflect.Descriptor instead.
func (*GetBundleKeysRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{4}
}

// GetBundleKeysResponse lists the bundle signing keys.
type GetBundleKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current, next and recently retired keys.
	Keys          []*BundleKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleKeysResponse) Reset() {
	*x = GetBundleKeysResponse{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleKeysResponse) ProtoMessage() {}

func (x *GetBundleKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleKeysResponse.ProtoReflect.Descriptor instead.
func (*GetBundleKeysResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *GetBundleKeysResponse) GetKeys() []*BundleKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// BundleKey is a public key that verifies bundle signatures.
type BundleKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key ID used in the JWS header ("kid").
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// The JWS algorithm, "EdDSA" (Ed25519 keys) in v1alpha1.
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// The raw 32-byte Ed25519 public key.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The key's status.
	Status        BundleKeyStatus `protobuf:"varint,4,opt,name=status,proto3,enum=whitetower.module.v1alpha1.BundleKeyStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleKey) Reset() {
	*x = BundleKey{}
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleKey) ProtoMessage() {}

func (x *BundleKey) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleKey.ProtoReflect.Descriptor instead.
func (*BundleKey) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *BundleKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *BundleKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *BundleKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *BundleKey) GetStatus() BundleKeyStatus {
	if x != nil {
		return x.Status
	}
	return BundleKeyStatus_BUNDLE_KEY_STATUS_UNSPECIFIED
}

var File_whitetower_module_v1alpha1_policy_proto protoreflect.FileDescriptor

const file_whitetower_module_v1alpha1_policy_proto_rawDesc = "" +
	"\n" +
	"'whitetower/module/v1alpha1/policy.proto\x12\x1awhitetower.module.v1alpha1\"G\n" +
	"\x10GetBundleRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"O\n" +
	"\x11GetBundleResponse\x12:\n" +
	"\x06bundle\x18\x01 \x01(\v2\".whitetower.module.v1alpha1.BundleR\x06bundle\"\x80\x01\n" +
	"\x06Bundle\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12<\n" +
	"\x05files\x18\x03 \x03(\v2&.whitetower.module.v1alpha1.BundleFileR\x05files\":\n" +
	"\n" +
	"BundleFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x16\n" +
	"\x14GetBundleKeysRequest\"R\n" +
	"\x15GetBundleKeysResponse\x129\n" +
	"\x04keys\x18\x01 \x03(\v2%.whitetower.module.v1alpha1.BundleKeyR\x04keys\"\xa4\x01\n" +
	"\tBundleKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12C\n" +
	"\x06status\x18\x04 \x01(\x0e2+.whitetower.module.v1alpha1.BundleKeyStatusR\x06status*\x8d\x01\n" +
	"\x0fBundleKeyStatus\x12!\n" +
	"\x1dBUNDLE_KEY_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BUNDLE_KEY_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16BUNDLE_KEY_STATUS_NEXT\x10\x02\x12\x1d\n" +
	"\x19BUNDLE_KEY_STATUS_RETIRED\x10\x032\xf9\x01\n" +
	"\rPolicyService\x12m\n" +
	"\tGetBundle\x12,.whitetower.module.v1alpha1.GetBundleRequest\x1a-.whitetower.module.v1alpha1.GetBundleResponse\"\x03\x90\x02\x01\x12y\n" +
	"\rGetBundleKeys\x120.whitetower.module.v1alpha1.GetBundleKeysRequest\x1a1.whitetower.module.v1alpha1.GetBundleKeysResponse\"\x03\x90\x02\x01B\x8c\x02\n" +
	"\x1ecom.whitetower.module.v1alpha1B\vPolicyProtoP\x01ZSgithub.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1;modulev1alpha1\xa2\x02\x03WMX\xaa\x02\x1aWhitetower.Module.V1alpha1\xca\x02\x1aWhitetower\\Module\\V1alpha1\xe2\x02&Whitetower\\Module\\V1alpha1\\GPBMetadata\xea\x02\x1cWhitetower::Module::V1alpha1b\x06proto3"

var (
	file_whitetower_module_v1alpha1_policy_proto_rawDescOnce sync.Once
	file_whitetower_module_v1alpha1_policy_proto_rawDescData []byte
)

func file_whitetower_module_v1alpha1_policy_proto_rawDescGZIP() []byte {
	file_whitetower_module_v1alpha1_policy_proto_rawDescOnce.Do(func() {
		file_whitetower_module_v1alpha1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_policy_proto_rawDesc), len(file_whitetower_module_v1alpha1_policy_proto_rawDesc)))
	})
	return file_whitetower_module_v1alpha1_policy_proto_rawDescData
}

var file_whitetower_module_v1alpha1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whitetower_module_v1alpha1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_whitetower_module_v1alpha1_policy_proto_goTypes = []any{
	(BundleKeyStatus)(0),          // 0: whitetower.module.v1alpha1.BundleKeyStatus
	(*GetBundleRequest)(nil),      // 1: whitetower.module.v1alpha1.GetBundleRequest
	(*GetBundleResponse)(nil),     // 2: whitetower.module.v1alpha1.GetBundleResponse
	(*Bundle)(nil),                // 3: whitetower.module.v1alpha1.Bundle
	(*BundleFile)(nil),            // 4: whitetower.module.v1alpha1.BundleFile
	(*GetBundleKeysRequest)(nil),  // 5: whitetower.module.v1alpha1.GetBundleKeysRequest
	(*GetBundleKeysResponse)(nil), // 6: whitetower.module.v1alpha1.GetBundleKeysResponse
	(*BundleKey)(nil),             // 7: whitetower.module.v1alpha1.BundleKey
}
var file_whitetower_module_v1alpha1_policy_proto_depIdxs = []int32{
	3, // 0: whitetower.module.v1alpha1.GetBundleResponse.bundle:type_name -> whitetower.module.v1alpha1.Bundle
	4, // 1: whitetower.module.v1alpha1.Bundle.files:type_name -> whitetower.module.v1alpha1.BundleFile
	7, // 2: whitetower.module.v1alpha1.GetBundleKeysResponse.keys:type_name -> whitetower.module.v1alpha1.BundleKey
	0, // 3: whitetower.module.v1alpha1.BundleKey.status:type_name -> whitetower.module.v1alpha1.BundleKeyStatus
	1, // 4: whitetower.module.v1alpha1.PolicyService.GetBundle:input_type -> whitetower.module.v1alpha1.GetBundleRequest
	5, // 5: whitetower.module.v1alpha1.PolicyService.GetBundleKeys:input_type -> whitetower.module.v1alpha1.GetBundleKeysRequest
	2, // 6: whitetower.module.v1alpha1.PolicyService.GetBundle:output_type -> whitetower.module.v1alpha1.GetBundleResponse
	6, // 7: whitetower.module.v1alpha1.PolicyService.GetBundleKeys:output_type -> whitetower.module.v1alpha1.GetBundleKeysResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_whitetower_module_v1alpha1_policy_proto_init() }
func file_whitetower_module_v1alpha1_policy_proto_init() {
	if File_whitetower_module_v1alpha1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_policy_proto_rawDesc), len(file_whitetower_module_v1alpha1_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitetower_module_v1alpha1_policy_proto_goTypes,
		DependencyIndexes: file_whitetower_module_v1alpha1_policy_proto_depIdxs,
		EnumInfos:         file_whitetower_module_v1alpha1_policy_proto_enumTypes,
		MessageInfos:      file_whitetower_module_v1alpha1_policy_proto_msgTypes,
	}.Build()
	File_whitetower_module_v1alpha1_policy_proto = out.File
	file_whitetower_module_v1alpha1_policy_proto_goTypes = nil
	file_whitetower_module_v1alpha1_policy_proto_depIdxs = nil
}
