// Module contracts v0.1 (RFC-0001): instance registration.
// Normative text: docs/contracts/module-contract-v0.1.md, section 4.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: whitetower/module/v1alpha1/registry.proto

package modulev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health is the health an instance reports about itself.
type Health int32

const (
	// Not reported. Treated as unhealthy.
	Health_HEALTH_UNSPECIFIED Health = 0
	// Working normally.
	Health_HEALTH_HEALTHY Health = 1
	// Working, with a problem an operator should look at, for example events
	// rejected by the core.
	Health_HEALTH_DEGRADED Health = 2
	// Not working; its gate is closed or its layer cannot be applied.
	Health_HEALTH_UNHEALTHY Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_UNHEALTHY",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_HEALTHY":     1,
		"HEALTH_DEGRADED":    2,
		"HEALTH_UNHEALTHY":   3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_whitetower_module_v1alpha1_registry_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_whitetower_module_v1alpha1_registry_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{0}
}

// RegisterInstanceRequest describes the instance.
type RegisterInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slug of the module, as registered and approved by an operator.
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Lowercase hexadecimal SHA-256 of the RFC 8785 canonical JSON of the manifest
	// the instance runs. It must match the approved manifest.
	ManifestSha256 string `protobuf:"bytes,2,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	// Version of the module, as in its manifest.
	ModuleVersion string `protobuf:"bytes,3,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`
	// Key chosen by the instance, unique within the module and stable for its
	// deployment slot (for example a pod name). Registering again with the same
	// key updates the existing instance.
	InstanceKey string `protobuf:"bytes,4,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"`
	// Contract versions the instance supports, for example "v1alpha1".
	ContractVersions []string `protobuf:"bytes,5,rep,name=contract_versions,json=contractVersions,proto3" json:"contract_versions,omitempty"`
	// Agents the instance serves. An enforcement point embedded in an agent's
	// process lists exactly that agent.
	AgentIds []string `protobuf:"bytes,6,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	// Descriptive information, shown in the console.
	Info          *InstanceInfo `protobuf:"bytes,7,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInstanceRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RegisterInstanceRequest) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *RegisterInstanceRequest) GetModuleVersion() string {
	if x != nil {
		return x.ModuleVersion
	}
	return ""
}

func (x *RegisterInstanceRequest) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

func (x *RegisterInstanceRequest) GetContractVersions() []string {
	if x != nil {
		return x.ContractVersions
	}
	return nil
}

func (x *RegisterInstanceRequest) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *RegisterInstanceRequest) GetInfo() *InstanceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// InstanceInfo is descriptive information about an instance. It is never used
// for authorization.
type InstanceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host or pod name.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Versions of the main components, for example {"python": "3.13.1", "langgraph": "1.2.0"}.
	Components    map[string]string `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InstanceInfo) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

// RegisterInstanceResponse confirms the registration.
type RegisterInstanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier the core assigned to the instance (UUIDv7). Every later call
	// carries it.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// The contract version selected for this instance.
	ContractVersion string `protobuf:"bytes,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	// How often the instance must call Heartbeat.
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterInstanceResponse) Reset() {
	*x = RegisterInstanceResponse{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceResponse) ProtoMessage() {}

func (x *RegisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterInstanceResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *RegisterInstanceResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

// HeartbeatRequest reports the instance's health.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier returned by RegisterInstance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Current health.
	Health Health `protobuf:"varint,2,opt,name=health,proto3,enum=whitetower.module.v1alpha1.Health" json:"health,omitempty"`
	// Short explanation of the health, for operators.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// The complete set of agents the instance serves now. Present only when the
	// set changed since the last report.
	ServedAgents  *ServedAgents `protobuf:"bytes,4,opt,name=served_agents,json=servedAgents,proto3" json:"served_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *HeartbeatRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HeartbeatRequest) GetServedAgents() *ServedAgents {
	if x != nil {
		return x.ServedAgents
	}
	return nil
}

// ServedAgents is a complete set of agent IDs.
type ServedAgents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent IDs.
	AgentIds      []string `protobuf:"bytes,1,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServedAgents) Reset() {
	*x = ServedAgents{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServedAgents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServedAgents) ProtoMessage() {}

func (x *ServedAgents) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServedAgents.ProtoReflect.Descriptor instead.
func (*ServedAgents) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ServedAgents) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

// HeartbeatResponse may change the heartbeat interval.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How often the instance must call Heartbeat from now on.
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

// DeregisterInstanceRequest names the instance that is stopping.
type DeregisterInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier returned by RegisterInstance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Why the instance is stopping, for operators.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInstanceRequest) Reset() {
	*x = DeregisterInstanceRequest{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInstanceRequest) ProtoMessage() {}

func (x *DeregisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterInstanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DeregisterInstanceResponse is empty.
type DeregisterInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterInstanceResponse) Reset() {
	*x = DeregisterInstanceResponse{}
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterInstanceResponse) ProtoMessage() {}

func (x *DeregisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitetower_module_v1alpha1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP(), []int{7}
}

var File_whitetower_module_v1alpha1_registry_proto protoreflect.FileDescriptor

const file_whitetower_module_v1alpha1_registry_proto_rawDesc = "" +
	"\n" +
	")whitetower/module/v1alpha1/registry.proto\x12\x1awhitetower.module.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\"\xac\x02\n" +
	"\x17RegisterInstanceRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12'\n" +
	"\x0fmanifest_sha256\x18\x02 \x01(\tR\x0emanifestSha256\x12%\n" +
	"\x0emodule_version\x18\x03 \x01(\tR\rmoduleVersion\x12!\n" +
	"\finstance_key\x18\x04 \x01(\tR\vinstanceKey\x12+\n" +
	"\x11contract_versions\x18\x05 \x03(\tR\x10contractVersions\x12\x1b\n" +
	"\tagent_ids\x18\x06 \x03(\tR\bagentIds\x12<\n" +
	"\x04info\x18\a \x01(\v2(.whitetower.module.v1alpha1.InstanceInfoR\x04info\"\xbb\x01\n" +
	"\fInstanceInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12X\n" +
	"\n" +
	"components\x18\x02 \x03(\v28.whitetower.module.v1alpha1.InstanceInfo.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x18RegisterInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\x10contract_version\x18\x02 \x01(\tR\x0fcontractVersion\x12H\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"\xd6\x01\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12:\n" +
	"\x06health\x18\x02 \x01(\x0e2\".whitetower.module.v1alpha1.HealthR\x06health\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12M\n" +
	"\rserved_agents\x18\x04 \x01(\v2(.whitetower.module.v1alpha1.ServedAgentsR\fservedAgents\"+\n" +
	"\fServedAgents\x12\x1b\n" +
	"\tagent_ids\x18\x01 \x03(\tR\bagentIds\"]\n" +
	"\x11HeartbeatResponse\x12H\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"T\n" +
	"\x19DeregisterInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1c\n" +
	"\x1aDeregisterInstanceResponse*_\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x032\x90\x03\n" +
	"\x0fRegistryService\x12\x82\x01\n" +
	"\x10RegisterInstance\x123.whitetower.module.v1alpha1.RegisterInstanceRequest\x1a4.whitetower.module.v1alpha1.RegisterInstanceResponse\"\x03\x90\x02\x02\x12m\n" +
	"\tHeartbeat\x12,.whitetower.module.v1alpha1.HeartbeatRequest\x1a-.whitetower.module.v1alpha1.HeartbeatResponse\"\x03\x90\x02\x02\x12\x88\x01\n" +
	"\x12DeregisterInstance\x125.whitetower.module.v1alpha1.DeregisterInstanceRequest\x1a6.whitetower.module.v1alpha1.DeregisterInstanceResponse\"\x03\x90\x02\x02B\x8e\x02\n" +
	"\x1ecom.whitetower.module.v1alpha1B\rRegistryProtoP\x01ZSgithub.com/J466Y/WhiteTower/pkg/moduleapi/whitetower/module/v1alpha1;modulev1alpha1\xa2\x02\x03WMX\xaa\x02\x1aWhitetower.Module.V1alpha1\xca\x02\x1aWhitetower\\Module\\V1alpha1\xe2\x02&Whitetower\\Module\\V1alpha1\\GPBMetadata\xea\x02\x1cWhitetower::Module::V1alpha1b\x06proto3"

var (
	file_whitetower_module_v1alpha1_registry_proto_rawDescOnce sync.Once
	file_whitetower_module_v1alpha1_registry_proto_rawDescData []byte
)

func file_whitetower_module_v1alpha1_registry_proto_rawDescGZIP() []byte {
	file_whitetower_module_v1alpha1_registry_proto_rawDescOnce.Do(func() {
		file_whitetower_module_v1alpha1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_registry_proto_rawDesc), len(file_whitetower_module_v1alpha1_registry_proto_rawDesc)))
	})
	return file_whitetower_module_v1alpha1_registry_proto_rawDescData
}

var file_whitetower_module_v1alpha1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whitetower_module_v1alpha1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_whitetower_module_v1alpha1_registry_proto_goTypes = []any{
	(Health)(0),                        // 0: whitetower.module.v1alpha1.Health
	(*RegisterInstanceRequest)(nil),    // 1: whitetower.module.v1alpha1.RegisterInstanceRequest
	(*InstanceInfo)(nil),               // 2: whitetower.module.v1alpha1.InstanceInfo
	(*RegisterInstanceResponse)(nil),   // 3: whitetower.module.v1alpha1.RegisterInstanceResponse
	(*HeartbeatRequest)(nil),           // 4: whitetower.module.v1alpha1.HeartbeatRequest
	(*ServedAgents)(nil),               // 5: whitetower.module.v1alpha1.ServedAgents
	(*HeartbeatResponse)(nil),          // 6: whitetower.module.v1alpha1.HeartbeatResponse
	(*DeregisterInstanceRequest)(nil),  // 7: whitetower.module.v1alpha1.DeregisterInstanceRequest
	(*DeregisterInstanceResponse)(nil), // 8: whitetower.module.v1alpha1.DeregisterInstanceResponse
	nil,                                // 9: whitetower.module.v1alpha1.InstanceInfo.ComponentsEntry
	(*durationpb.Duration)(nil),        // 10: google.protobuf.Duration
}
var file_whitetower_module_v1alpha1_registry_proto_depIdxs = []int32{
	2,  // 0: whitetower.module.v1alpha1.RegisterInstanceRequest.info:type_name -> whitetower.module.v1alpha1.InstanceInfo
	9,  // 1: whitetower.module.v1alpha1.InstanceInfo.components:type_name -> whitetower.module.v1alpha1.InstanceInfo.ComponentsEntry
	10, // 2: whitetower.module.v1alpha1.RegisterInstanceResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	0,  // 3: whitetower.module.v1alpha1.HeartbeatRequest.health:type_name -> whitetower.module.v1alpha1.Health
	5,  // 4: whitetower.module.v1alpha1.HeartbeatRequest.served_agents:type_name -> whitetower.module.v1alpha1.ServedAgents
	10, // 5: whitetower.module.v1alpha1.HeartbeatResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	1,  // 6: whitetower.module.v1alpha1.RegistryService.RegisterInstance:input_type -> whitetower.module.v1alpha1.RegisterInstanceRequest
	4,  // 7: whitetower.module.v1alpha1.RegistryService.Heartbeat:input_type -> whitetower.module.v1alpha1.HeartbeatRequest
	7,  // 8: whitetower.module.v1alpha1.RegistryService.DeregisterInstance:input_type -> whitetower.module.v1alpha1.DeregisterInstanceRequest
	3,  // 9: whitetower.module.v1alpha1.RegistryService.RegisterInstance:output_type -> whitetower.module.v1alpha1.RegisterInstanceResponse
	6,  // 10: whitetower.module.v1alpha1.RegistryService.Heartbeat:output_type -> whitetower.module.v1alpha1.HeartbeatResponse
	8,  // 11: whitetower.module.v1alpha1.RegistryService.DeregisterInstance:output_type -> whitetower.module.v1alpha1.DeregisterInstanceResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_whitetower_module_v1alpha1_registry_proto_init() }
func file_whitetower_module_v1alpha1_registry_proto_init() {
	if File_whitetower_module_v1alpha1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitetower_module_v1alpha1_registry_proto_rawDesc), len(file_whitetower_module_v1alpha1_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitetower_module_v1alpha1_registry_proto_goTypes,
		DependencyIndexes: file_whitetower_module_v1alpha1_registry_proto_depIdxs,
		EnumInfos:         file_whitetower_module_v1alpha1_registry_proto_enumTypes,
		MessageInfos:      file_whitetower_module_v1alpha1_registry_proto_msgTypes,
	}.Build()
	File_whitetower_module_v1alpha1_registry_proto = out.File
	file_whitetower_module_v1alpha1_registry_proto_goTypes = nil
	file_whitetower_module_v1alpha1_registry_proto_depIdxs = nil
}
