// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ensurePartitions = `-- name: EnsurePartitions :exec
SELECT whitetower.ensure_audit_partitions($1::integer)
`

// Creates the partitions of the audit tables for this month and the next
// months_ahead.
func (q *Queries) EnsurePartitions(ctx context.Context, monthsAhead int32) error {
	_, err := q.db.Exec(ctx, ensurePartitions, monthsAhead)
	return err
}

const recordEvent = `-- name: RecordEvent :exec
WITH stored AS (
  INSERT INTO whitetower.audit_events (
    id, source, event_id, type, event_time, subject_agent_id,
    actor_type, actor_id, action, outcome, reason, request_id, trace_id, canonical)
  VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14)
  RETURNING id, ingested_at
)
INSERT INTO whitetower.audit_unsealed (audit_id, ingested_at)
SELECT id, ingested_at FROM stored
`

type RecordEventParams struct {
	ID             uuid.UUID
	Source         string
	EventID        string
	Type           string
	EventTime      time.Time
	SubjectAgentID *uuid.UUID
	ActorType      string
	ActorID        *string
	Action         string
	Outcome        *string
	Reason         *string
	RequestID      *string
	TraceID        *string
	Canonical      []byte
}

// Records an event, and queues it for the sealer, in the caller's
// transaction.
func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.ID,
		arg.Source,
		arg.EventID,
		arg.Type,
		arg.EventTime,
		arg.SubjectAgentID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Outcome,
		arg.Reason,
		arg.RequestID,
		arg.TraceID,
		arg.Canonical,
	)
	return err
}
