// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package auditdb

import (
	"context"
)

// iteratorForInsertLeaves implements pgx.CopyFromSource.
type iteratorForInsertLeaves struct {
	rows                 []InsertLeavesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLeaves) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLeaves) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LeafIndex,
		r.rows[0].AuditID,
		r.rows[0].IngestedAt,
		r.rows[0].LeafHash,
		r.rows[0].SealedAt,
	}, nil
}

func (r iteratorForInsertLeaves) Err() error {
	return nil
}

func (q *Queries) InsertLeaves(ctx context.Context, arg []InsertLeavesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"whitetower", "audit_leaves"}, []string{"leaf_index", "audit_id", "ingested_at", "leaf_hash", "sealed_at"}, &iteratorForInsertLeaves{rows: arg})
}

// iteratorForInsertTreeHashes implements pgx.CopyFromSource.
type iteratorForInsertTreeHashes struct {
	rows                 []InsertTreeHashesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTreeHashes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTreeHashes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].HashIndex,
		r.rows[0].Hash,
	}, nil
}

func (r iteratorForInsertTreeHashes) Err() error {
	return nil
}

func (q *Queries) InsertTreeHashes(ctx context.Context, arg []InsertTreeHashesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"whitetower", "audit_tree_hashes"}, []string{"hash_index", "hash"}, &iteratorForInsertTreeHashes{rows: arg})
}
