// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sealer.sql

package auditdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateCheckpointKey = `-- name: ActivateCheckpointKey :exec
UPDATE whitetower.signing_keys SET status = 'active', activated_at = now(), retired_at = NULL
WHERE key_id = $1 AND status <> 'active'
`

func (q *Queries) ActivateCheckpointKey(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, activateCheckpointKey, keyID)
	return err
}

const addCheckpointKey = `-- name: AddCheckpointKey :exec
INSERT INTO whitetower.signing_keys (key_id, purpose, algorithm, public_jwk, status)
VALUES ($1, 'checkpoint', $2, $3, 'next')
ON CONFLICT (key_id) DO NOTHING
`

type AddCheckpointKeyParams struct {
	KeyID     string
	Algorithm string
	PublicJwk []byte
}

// Registers the public half of a checkpoint key, unless it is already.
func (q *Queries) AddCheckpointKey(ctx context.Context, arg AddCheckpointKeyParams) error {
	_, err := q.db.Exec(ctx, addCheckpointKey, arg.KeyID, arg.Algorithm, arg.PublicJwk)
	return err
}

const canonicalEvents = `-- name: CanonicalEvents :many
SELECT id, canonical FROM whitetower.audit_events WHERE id = ANY($1::uuid[])
`

type CanonicalEventsRow struct {
	ID        uuid.UUID
	Canonical []byte
}

// The canonical bytes of events, by their audit IDs.
func (q *Queries) CanonicalEvents(ctx context.Context, ids []uuid.UUID) ([]CanonicalEventsRow, error) {
	rows, err := q.db.Query(ctx, canonicalEvents, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CanonicalEventsRow
	for rows.Next() {
		var i CanonicalEventsRow
		if err := rows.Scan(&i.ID, &i.Canonical); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUnsealed = `-- name: ClaimUnsealed :many
DELETE FROM whitetower.audit_unsealed
WHERE audit_id IN (
  SELECT q.audit_id FROM whitetower.audit_unsealed q ORDER BY q.ingested_at, q.audit_id LIMIT $1)
RETURNING audit_id, ingested_at
`

// Takes the next events off the queue of events to seal, without row locks:
// one sealer runs, and if a second one ever did, the primary key of the
// leaves would refuse one of their batches.
func (q *Queries) ClaimUnsealed(ctx context.Context, maxEvents int32) ([]WhitetowerAuditUnsealed, error) {
	rows, err := q.db.Query(ctx, claimUnsealed, maxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhitetowerAuditUnsealed
	for rows.Next() {
		var i WhitetowerAuditUnsealed
		if err := rows.Scan(&i.AuditID, &i.IngestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec
INSERT INTO whitetower.audit_checkpoints (tree_size, root_hash, signed_note, key_id)
VALUES ($1, $2, $3, $4)
`

type InsertCheckpointParams struct {
	TreeSize   int64
	RootHash   []byte
	SignedNote string
	KeyID      string
}

func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.db.Exec(ctx, insertCheckpoint,
		arg.TreeSize,
		arg.RootHash,
		arg.SignedNote,
		arg.KeyID,
	)
	return err
}

type InsertLeavesParams struct {
	LeafIndex  int64
	AuditID    uuid.UUID
	IngestedAt time.Time
	LeafHash   []byte
	SealedAt   time.Time
}

type InsertTreeHashesParams struct {
	HashIndex int64
	Hash      []byte
}

const latestCheckpoint = `-- name: LatestCheckpoint :one
SELECT tree_size, created_at FROM whitetower.audit_checkpoints ORDER BY tree_size DESC LIMIT 1
`

type LatestCheckpointRow struct {
	TreeSize  int64
	CreatedAt time.Time
}

func (q *Queries) LatestCheckpoint(ctx context.Context) (LatestCheckpointRow, error) {
	row := q.db.QueryRow(ctx, latestCheckpoint)
	var i LatestCheckpointRow
	err := row.Scan(&i.TreeSize, &i.CreatedAt)
	return i, err
}

const retireOtherCheckpointKeys = `-- name: RetireOtherCheckpointKeys :exec
UPDATE whitetower.signing_keys SET status = 'retired', retired_at = now()
WHERE purpose = 'checkpoint' AND status = 'active' AND key_id <> $1
`

// Retires the checkpoint keys other than key_id. Their public halves stay,
// so that the checkpoints they signed still verify.
func (q *Queries) RetireOtherCheckpointKeys(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, retireOtherCheckpointKeys, keyID)
	return err
}

const sealingTime = `-- name: SealingTime :one
SELECT clock_timestamp()::timestamptz AS now
`

// The database's clock, for the leaves of a batch.
func (q *Queries) SealingTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, sealingTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const treeHashes = `-- name: TreeHashes :many
SELECT hash_index, hash FROM whitetower.audit_tree_hashes WHERE hash_index = ANY($1::bigint[])
`

func (q *Queries) TreeHashes(ctx context.Context, indexes []int64) ([]WhitetowerAuditTreeHash, error) {
	rows, err := q.db.Query(ctx, treeHashes, indexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhitetowerAuditTreeHash
	for rows.Next() {
		var i WhitetowerAuditTreeHash
		if err := rows.Scan(&i.HashIndex, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const treeSize = `-- name: TreeSize :one
SELECT (coalesce(max(leaf_index), -1) + 1)::bigint AS size FROM whitetower.audit_leaves
`

// The number of leaves in the tree.
func (q *Queries) TreeSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, treeSize)
	var size int64
	err := row.Scan(&size)
	return size, err
}
